In [1]:
%load_ext autoreload
%autoreload 2
    
from scipy.stats import norm
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from statsmodels.base.model import GenericLikelihoodModel
import scipy.stats as stats
import sys

sys.path.append("../")
import vuong_tests10 as vuong_tests_fast
from vuong_test_base import *


In [2]:
class JointNormal1(GenericLikelihoodModel):
    
    def loglikeobs(self, params):
        data = np.concatenate([[self.endog],self.exog.transpose()],axis=0)
        mult_rv = stats.multivariate_normal([params[0], 0.0], [[1,0],[0,1]])
        return mult_rv.logpdf(data.transpose())
    
    
class JointNormal2(GenericLikelihoodModel):
    
    def loglikeobs(self, params):
        data = np.concatenate([[self.endog],self.exog.transpose()],axis=0)
        mult_rv = stats.multivariate_normal([0.0, params[0]], [[1,0],[0,1]])
        return mult_rv.logpdf(data.transpose())


def setup_shi(yn,xn):
    # model 1 grad, etc.
    nobs = yn.shape[0]
    model1_param = np.array([yn.mean()])
    model2_param = np.array([xn.mean()])
    
    model1_deriv = JointNormal1(yn,xn)
    ll1 = model1_deriv.loglikeobs(model1_param)
    grad1 =  model1_deriv.score_obs(model1_param).reshape( (nobs,1) )
    hess1 = model1_deriv.hessian(model1_param)
    
    model2_deriv = JointNormal2(yn,xn)
    ll2 = model2_deriv.loglikeobs(model2_param)
    grad2 =  model2_deriv.score_obs(model2_param).reshape( (nobs,1) )  
    hess2 = model2_deriv.hessian(model2_param)
    
    return ll1,grad1,hess1,model1_param,ll2,grad2,hess2,model2_param

def gen_data(beta= 1.5, nobs=1000):
    cov = [[25, 0], [0, 1]]
    data = np.random.multivariate_normal([beta,beta], [[25,0],[0,1]],  nobs)
    return data[:,0],data[:,1],nobs


yn,xn,nobs = gen_data()
ll1,grad1,hess1,params1,ll2,grad2,hess2,params2 = setup_shi(yn,xn)
print(grad1.shape,hess1.shape)
#NOTE! Weird size distortions with shi's test when theta = .5....

(1000, 1) (1, 1)


In [3]:
def sw_test_stat(ll1, grad1, hess1, params1, ll2, grad2, hess2, params2, epsilon=.5,compute_v=True,print_stuff=False):
    nobs = ll1.shape[0]

    idx_even = np.arange(0, nobs, 2)         # 0-based indices: 0,2,4,...
    idx_odd  = np.arange(1, nobs, 2)         # 1,3,5,...

    # Regular loglikelihood ratio statistic
    llr = (ll1 - ll2).sum()
    
    # Split-sample difference statistic
    llr_split = ll1[idx_even].sum() - ll2[idx_odd].sum()

    # Regularized numerator (as in your expression)
    llr_reg = llr + epsilon * llr_split

    # Main variance
    omega2 = (ll1 - ll2).var()
    
    # Split-group variances
    omega_A2 = ll1[idx_even].var()
    omega_B2 = ll2[idx_odd].var()

    # Regularized variance
    omega_reg2 = (1 + epsilon) * omega2 + (epsilon**2 / 2) * (omega_A2 + omega_B2)
    omega_reg = np.sqrt(omega_reg2)

    if print_stuff:
        print('llr',llr,llr_split)
        print('omega',omega2,omega_A2,omega_B2,np.sqrt(omega2),np.sqrt(omega_reg2))
    if not compute_v:
        return llr_reg,omega_reg,nobs 
        
    V = compute_eigen2(ll1, grad1, hess1, params1, ll2, grad2, hess2, params2) # If you want to try to bias-correct you can, this is optional
    return llr_reg,omega_reg,V,nobs 
        
    


def sw_test(ll1, grad1, hess1, params1, ll2, grad2, hess2, params2, epsilon=.5,
            alpha=.05,  biascorrect=False):

    llr_reg,omega_reg,V,nobs =  sw_test_stat(ll1, grad1, hess1, params1, ll2, grad2, hess2, params2, epsilon=.5)

    if biascorrect:
        llr_reg += V.sum() / 2

    test_stat = llr_reg / (omega_reg * np.sqrt(nobs))

    # Two-sided test
    reject_high = (test_stat >= norm.ppf(1 - alpha / 2))
    reject_low  = (test_stat <= norm.ppf(alpha / 2))
    return int(reject_high) + 2 * int(reject_low)

    
yn,xn,nobs = gen_data()
ll1,grad1,hess1,params1,ll2,grad2,hess2,params2 = setup_shi(yn,xn)
print(grad1.shape,hess1.shape)

(1000, 1) (1, 1)


In [4]:
def bootstrap_distr(setup_shi,yn, xn,
                    epsilon=0.5, trials=500, seed=None, biascorrect=False):

    ll1, grad1, hess1, params1, ll2, grad2, hess2, params2 = setup_shi(yn,xn)
    nobs = ll1.shape[0]
    #print('---------')
    llr_reg, omega_reg, V, nobs = sw_test_stat(
        ll1, grad1, hess1, params1, ll2, grad2, hess2, params2, epsilon=epsilon,print_stuff=False
    )
    if biascorrect:
        llr_reg += V.sum() / 2
    test_stat = llr_reg / (omega_reg * np.sqrt(nobs))
    stat_dist = []

    test_stat0 = (ll1-ll2).sum()/np.sqrt( nobs*(ll1-ll2).var() )
    stats_s0 = []
    
    
    for i in range(trials):
        if seed is not None:
            np.random.seed(seed + i)
        sample = np.random.choice(np.arange(nobs), nobs, replace=True)
        #print(sample.shape,nobs)
        ll1_s, _, _, _, ll2_s, _, _, _ = setup_shi(yn[sample],xn[sample])
        
        #print('inner', ll1.mean(),ll2.mean(),ll1.var(),ll2.var())
        #print(ll1_s.mean(),ll2_s.mean(),ll1_s.var(),ll2_s.var())
        #print('------')
        
        # Don't need V for bootstrap stats (saves computation)
        llr_reg_s, omega_reg_s, nobs_in_s = sw_test_stat(
            ll1_s, grad1, hess1, params1, ll2_s, grad2, hess2, params2, epsilon=epsilon, compute_v=False,print_stuff=False
        )

        # bias correct V not directly available for bootstrap
        stat_s = (llr_reg_s - llr_reg)/ (omega_reg_s * np.sqrt(nobs_in_s))
        stat_dist.append(stat_s)

        ###### real stat for comparison...
        llrs0 = ll1_s - ll2_s
        stats_s0.append(  llrs0.sum()/  np.sqrt(nobs*llrs0.var()) )
    if False:
        print('test_stat0', nobs_in_s, nobs, (np.array(stats_s0)-test_stat0).mean(),np.array(stats_s0).mean(),test_stat0 )
        print('test_stat', nobs_in_s, nobs, (np.array(stat_dist)-test_stat).mean(),np.array(stat_dist).mean(),test_stat )
    #print('----')
    return np.array(stat_dist), test_stat

def sw_bs_test_helper(stat_dist, stat_obs, alpha=.05, left=True, right=True, print_stuff=False):
    cv_upper = np.percentile(stat_dist, 100 * (1 - alpha / 2))
    cv_lower = np.percentile(stat_dist, 100 * (alpha / 2))
    if print_stuff:
        print(f"mean={stat_dist.mean():.3f}, cv_lower={cv_lower:.3f}, stat_obs={stat_obs:.3f}, cv_upper={cv_upper:.3f}")
    out = 0
    if right and (stat_obs > cv_upper):
        out = 1
    if left and (stat_obs < cv_lower):
        out += 2
    return out

def sw_bs_test(setup_shi,yn, xn,
               alpha=.05, trials=500, epsilon=0.5, biascorrect=False, seed=None, print_stuff=False):
    stat_dist, test_stat = bootstrap_distr(setup_shi,yn, xn,
        epsilon=epsilon, trials=trials, seed=seed, biascorrect=biascorrect
    )
    return sw_bs_test_helper(stat_dist, test_stat, alpha=alpha, print_stuff=print_stuff)

# Example Usage:
# result = sw_bs_test(ll1, grad1, hess1, params1, ll2, grad2, hess2, params2, epsilon=0.5, trials=1000)

In [5]:
def monte_carlo2(total, gen_data, setup_shi, alpha=.05,  c1=.5,trials=100, biascorrect=False):
    # Count for [model1, tie, model2] for each test
    reg = np.zeros(3, dtype=int)
    sw  = np.zeros(3, dtype=int)
    swbs = np.zeros(3, dtype=int)

    # Tracking statistics
    llr_sum = 0.0
    llr_sq_sum = 0.0
    omega_sum = 0.0
    nobs_last = None

    for _ in range(total):
        np.random.seed()
        yn, xn, nobs = gen_data()

        ll1, grad1, hess1, params1, ll2, grad2, hess2, params2 = setup_shi(yn, xn)
        #print('outer', ll1.mean(),ll2.mean(),ll1.var(),ll2.var())
        # Update LLR-related stats
        llrn = (ll1 - ll2).sum()
        omegan = np.sqrt((ll1 - ll2).var())
        llr_sum   += llrn
        llr_sq_sum += llrn ** 2
        omega_sum += omegan
        nobs_last = nobs

        # Run the tests
        reg_idx = regular_test(
            ll1, grad1, hess1, params1,
            ll2, grad2, hess2, params2,
            biascorrect=biascorrect, alpha=alpha
        )
        sw_idx = sw_test(
            ll1, grad1, hess1, params1,
            ll2, grad2, hess2, params2, epsilon = c1,
            alpha=alpha, biascorrect=biascorrect
        )
        swbs_idx = sw_bs_test(setup_shi,yn, xn, epsilon = c1, trials=trials,
            alpha=alpha, biascorrect=biascorrect, print_stuff=False
        )

        reg[reg_idx]   += 1
        sw[sw_idx]     += 1
        swbs[swbs_idx] += 1

    # Convert counts to rates/frequencies
    reg_freq = reg / total
    sw_freq = sw / total
    swbs_freq = swbs / total

    llr_mean = llr_sum / total
    llr_sd   = np.sqrt(llr_sq_sum / total - llr_mean ** 2)
    omega_scaled = omega_sum * np.sqrt(nobs_last) / total if nobs_last is not None else np.nan

    return reg_freq, sw_freq, swbs_freq, llr_mean, llr_sd, omega_scaled


In [6]:
nobs = 250
num_sims = 100
c1 = .1
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn)

gen_data_ex = lambda : gen_data(nobs=nobs,beta=0)
mc_out = monte_carlo2(num_sims,gen_data_ex,setup_shi_ex,c1=c1)
print(mc_out)

(array([1., 0., 0.]), array([0.97, 0.03, 0.  ]), array([0.71, 0.19, 0.1 ]), np.float64(11.242377920697999), np.float64(15.470319863054648), np.float64(19.498994354187612))


In [7]:
def gen_data3(beta= 1.5, nobs=1000):
    cov = [[25, 0], [0, 1]]
    data = np.random.multivariate_normal([0,beta], [[25,0],[0,1]],  nobs)
    return data[:,0],data[:,1],nobs

gen_data_ex = lambda : gen_data3(nobs=nobs,beta=.5)
mc_out = monte_carlo2(num_sims,gen_data_ex,setup_shi_ex,c1=c1)
print(mc_out)

(array([0.66, 0.  , 0.34]), array([0.96, 0.01, 0.03]), array([0.72, 0.02, 0.26]), np.float64(-15.126555146091446), np.float64(23.211785552736224), np.float64(26.153026536645875))


# size

In [8]:
gen_data_ex = lambda : gen_data(nobs=nobs,beta=.5)
mc_out = monte_carlo2(num_sims,gen_data_ex,setup_shi_ex,c1=c1)
print(mc_out)

(array([0.91, 0.  , 0.09]), array([0.98, 0.01, 0.01]), array([0.84, 0.05, 0.11]), np.float64(14.35273073374017), np.float64(44.54203579384977), np.float64(43.177163468258875))


In [9]:
gen_data_ex = lambda : gen_data(nobs=1000,beta=.5)
mc_out = monte_carlo2(num_sims,gen_data_ex,setup_shi_ex,c1=c1)
print(mc_out)

(array([0.96, 0.  , 0.04]), array([0.98, 0.  , 0.02]), array([0.76, 0.12, 0.12]), np.float64(19.532244040590232), np.float64(73.22089689345262), np.float64(83.93355990023429))


In [10]:
gen_data_ex = lambda : gen_data(nobs=nobs,beta=1.5)
mc_out = monte_carlo2(num_sims,gen_data_ex,setup_shi_ex,c1=c1)
print(mc_out)

(array([0.91, 0.01, 0.08]), array([0.95, 0.01, 0.04]), array([0.91, 0.04, 0.05]), np.float64(14.51251361738664), np.float64(134.32576672081944), np.float64(119.96502159834706))


In [11]:
gen_data_ex = lambda : gen_data(nobs=500,beta=.5)
mc_out = monte_carlo2(num_sims,gen_data_ex,setup_shi_ex,c1=c1)
print(mc_out)

(array([0.9, 0. , 0.1]), array([0.96, 0.01, 0.03]), array([0.77, 0.01, 0.22]), np.float64(4.25046302315288), np.float64(51.076623981415544), np.float64(55.78736381794692))


# power 0.... need to see...

In [12]:
gen_data_ex = lambda : gen_data3(nobs=nobs,beta=1.5)
mc_out = monte_carlo2(num_sims,gen_data_ex,setup_shi_ex,c1=c1)
print(mc_out)

(array([0., 0., 1.]), array([0.42, 0.  , 0.58]), array([0.01, 0.  , 0.99]), np.float64(-272.34787956358224), np.float64(29.69547762585258), np.float64(33.71974272509288))


In [13]:
gen_data_ex = lambda : gen_data3(nobs=500,beta=1.5)
mc_out = monte_carlo2(num_sims,gen_data_ex,setup_shi_ex,c1=c1)
print(mc_out)

(array([0., 0., 1.]), array([0.08, 0.  , 0.92]), array([0., 0., 1.]), np.float64(-552.4352726597405), np.float64(37.950024791224614), np.float64(41.0193082167744))
