In [46]:
%load_ext autoreload
%autoreload 2

from statsmodels.base.model import GenericLikelihoodModel

import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import scipy.stats as stats
import sys

from scipy.stats import multivariate_normal

sys.path.append("../")
import vuong_tests4

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [47]:
class JointNormal1(GenericLikelihoodModel):
    
    def loglikeobs(self, params):
        data = np.concatenate([[self.endog],self.exog.transpose()],axis=0)
        mult_rv = stats.multivariate_normal([params[0], 0.0], [[1,0],[0,1]])
        return mult_rv.logpdf(data.transpose())
    
    
class JointNormal2(GenericLikelihoodModel):
    
    def loglikeobs(self, params):
        data = np.concatenate([[self.endog],self.exog.transpose()],axis=0)
        mult_rv = stats.multivariate_normal([0.0, params[0]], [[1,0],[0,1]])
        return mult_rv.logpdf(data.transpose())


def setup_shi(yn,xn,return_model=False):
    # model 1 grad, etc.
    nobs = yn.shape[0]
    model1_param = np.array([yn.mean()])
    model2_param = np.array([xn.mean()])
    
    model1_deriv = JointNormal1(yn,xn)
    ll1 = model1_deriv.loglikeobs(model1_param)
    grad1 =  model1_deriv.score_obs(model1_param).reshape( (nobs,1) )
    hess1 = model1_deriv.hessian(model1_param)
    
    
    model2_deriv = JointNormal2(yn,xn)
    ll2 = model2_deriv.loglikeobs(model2_param)
    grad2 =  model2_deriv.score_obs(model2_param).reshape( (nobs,1) )  
    hess2 = model2_deriv.hessian(model2_param)
    if return_model:
        return ll1,grad1,hess1,params1,model1_deriv,ll2,grad2,hess2,params2,model2_deriv
    return ll1,grad1,hess1,model1_param,ll2,grad2,hess2,model2_param

def gen_data(beta= 1.5, nobs=1000):
    cov = [[25, 0], [0, 1]]
    data = np.random.multivariate_normal([beta,beta], [[25,0],[0,1]],  nobs)
    return data[:,0],data[:,1],nobs

yn,xn,nobs = gen_data()
ll1,grad1,hess1,params1,ll2,grad2,hess2,params2 = setup_shi(yn,xn)
print(grad1.shape,hess1.shape)

(1000, 1) (1, 1)


# Ex 0

In [48]:
beta = 0

In [49]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Shi (2015) \\ \hline \hline
No selection & 1.00 & 1.00 & 1.00 & 0.92   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.08   \\
\hline
\end{tabular}


llr:11.914205351663584, std:15.131168902446085
(array([1., 0., 0.]), array([1., 0., 0.]), array([1., 0., 0.]), array([0.92, 0.  , 0.08]), 11.914205351663584, 15.131168902446085)


In [50]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Shi (2015) \\ \hline \hline
No selection & 1.00 & 1.00 & 1.00 & 0.90   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.10   \\
\hline
\end{tabular}


llr:10.157371218536625, std:13.59265927332384
(array([1., 0., 0.]), array([1., 0., 0.]), array([1., 0., 0.]), array([0.9, 0. , 0.1]), 10.157371218536625, 13.59265927332384)


In [51]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=1000, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Shi (2015) \\ \hline \hline
No selection & 1.00 & 1.00 & 1.00 & 0.89   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.11   \\
\hline
\end{tabular}


llr:12.457736536328882, std:15.422082324382217
(array([1., 0., 0.]), array([1., 0., 0.]), array([1., 0., 0.]), array([0.89, 0.  , 0.11]), 12.457736536328882, 15.422082324382217)


# Ex 1

In [52]:
beta = 1

In [53]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Shi (2015) \\ \hline \hline
No selection & 0.95 & 0.94 & 0.94 & 1.00   \\
Model 1 & 0.00 & 0.03 & 0.03 & 0.00   \\
Model 2 & 0.05 & 0.03 & 0.03 & 0.00   \\
\hline
\end{tabular}


llr:12.315124457932475, std:86.35068825259843
(array([0.95, 0.  , 0.05]), array([0.94, 0.03, 0.03]), array([0.94, 0.03, 0.03]), array([1., 0., 0.]), 12.315124457932475, 86.35068825259843)


In [54]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Shi (2015) \\ \hline \hline
No selection & 0.95 & 0.93 & 0.93 & 0.98   \\
Model 1 & 0.01 & 0.04 & 0.04 & 0.00   \\
Model 2 & 0.04 & 0.03 & 0.03 & 0.02   \\
\hline
\end{tabular}


llr:8.968697864282134, std:113.67651479708712
(array([0.95, 0.01, 0.04]), array([0.93, 0.04, 0.03]), array([0.93, 0.04, 0.03]), array([0.98, 0.  , 0.02]), 8.968697864282134, 113.67651479708712)


In [ ]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=1000, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi)
vuong_tests4.print_mc(mc_out)
print(mc_out)

# Ex 2

In [38]:
beta = 1.5

In [39]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Shi (2015) \\ \hline \hline
No selection & 0.93 & 0.91 & 0.91 & 0.98   \\
Model 1 & 0.01 & 0.04 & 0.04 & 0.00   \\
Model 2 & 0.06 & 0.05 & 0.05 & 0.02   \\
\hline
\end{tabular}


llr:9.503972719807363, std:121.81194710770026
(array([0.93, 0.01, 0.06]), array([0.91, 0.04, 0.05]), array([0.91, 0.04, 0.05]), array([0.98, 0.  , 0.02]), 9.503972719807363, 121.81194710770026)


In [40]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Shi (2015) \\ \hline \hline
No selection & 0.91 & 0.90 & 0.90 & 1.00   \\
Model 1 & 0.03 & 0.06 & 0.06 & 0.00   \\
Model 2 & 0.06 & 0.04 & 0.04 & 0.00   \\
\hline
\end{tabular}


llr:22.220473681294735, std:195.72601782789584
(array([0.91, 0.03, 0.06]), array([0.9 , 0.06, 0.04]), array([0.9 , 0.06, 0.04]), array([1., 0., 0.]), 22.220473681294735, 195.72601782789584)


In [41]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=1000, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Shi (2015) \\ \hline \hline
No selection & 0.97 & 0.96 & 0.96 & 0.99   \\
Model 1 & 0.01 & 0.02 & 0.02 & 0.00   \\
Model 2 & 0.02 & 0.02 & 0.02 & 0.01   \\
\hline
\end{tabular}


llr:29.865227718668113, std:246.62287787500844
(array([0.97, 0.01, 0.02]), array([0.96, 0.02, 0.02]), array([0.96, 0.02, 0.02]), array([0.99, 0.  , 0.01]), 29.865227718668113, 246.62287787500844)


# Ex 3

In [42]:
beta = 2

In [43]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Shi (2015) \\ \hline \hline
No selection & 0.94 & 0.90 & 0.90 & 1.00   \\
Model 1 & 0.01 & 0.05 & 0.05 & 0.00   \\
Model 2 & 0.05 & 0.05 & 0.05 & 0.00   \\
\hline
\end{tabular}


llr:18.473060827593947, std:164.52314037981134
(array([0.94, 0.01, 0.05]), array([0.9 , 0.05, 0.05]), array([0.9 , 0.05, 0.05]), array([1., 0., 0.]), 18.473060827593947, 164.52314037981134)


In [44]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Shi (2015) \\ \hline \hline
No selection & 0.96 & 0.97 & 0.97 & 0.98   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.04 & 0.03 & 0.03 & 0.02   \\
\hline
\end{tabular}


llr:-2.3335614110046876, std:214.95499046006142
(array([0.96, 0.  , 0.04]), array([0.97, 0.  , 0.03]), array([0.97, 0.  , 0.03]), array([0.98, 0.  , 0.02]), -2.3335614110046876, 214.95499046006142)


In [45]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=1000, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Shi (2015) \\ \hline \hline
No selection & 0.92 & 0.90 & 0.90 & 1.00   \\
Model 1 & 0.00 & 0.02 & 0.02 & 0.00   \\
Model 2 & 0.08 & 0.08 & 0.08 & 0.00   \\
\hline
\end{tabular}


llr:-5.3213148863286905, std:336.38256732049445
(array([0.92, 0.  , 0.08]), array([0.9 , 0.02, 0.08]), array([0.9 , 0.02, 0.08]), array([1., 0., 0.]), -5.3213148863286905, 336.38256732049445)
