In [9]:
%load_ext autoreload
%autoreload 2

from statsmodels.base.model import GenericLikelihoodModel

import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import scipy.stats as stats
import sys

from scipy.stats import multivariate_normal

sys.path.append("../")
import vuong_tests4

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [10]:
class JointNormal1(GenericLikelihoodModel):
    
    def loglikeobs(self, params):
        data = np.concatenate([[self.endog],self.exog.transpose()],axis=0)
        mult_rv = stats.multivariate_normal([params[0], 0.0], [[1,0],[0,1]])
        return mult_rv.logpdf(data.transpose())
    
    
class JointNormal2(GenericLikelihoodModel):
    
    def loglikeobs(self, params):
        data = np.concatenate([[self.endog],self.exog.transpose()],axis=0)
        mult_rv = stats.multivariate_normal([0.0, params[0]], [[1,0],[0,1]])
        return mult_rv.logpdf(data.transpose())


def setup_shi(yn,xn,return_model=False):
    # model 1 grad, etc.
    nobs = yn.shape[0]
    model1_param = np.array([yn.mean()])
    model2_param = np.array([xn.mean()])
    
    model1_deriv = JointNormal1(yn,xn)
    ll1 = model1_deriv.loglikeobs(model1_param)
    grad1 =  model1_deriv.score_obs(model1_param).reshape( (nobs,1) )
    hess1 = model1_deriv.hessian(model1_param)
    
    
    model2_deriv = JointNormal2(yn,xn)
    ll2 = model2_deriv.loglikeobs(model2_param)
    grad2 =  model2_deriv.score_obs(model2_param).reshape( (nobs,1) )  
    hess2 = model2_deriv.hessian(model2_param)
    if return_model:
        return ll1,grad1,hess1,params1,model1_deriv,ll2,grad2,hess2,params2,model2_deriv
    return ll1,grad1,hess1,model1_param,ll2,grad2,hess2,model2_param

def gen_data(beta= 1.5, nobs=1000):
    cov = [[25, 0], [0, 1]]
    data = np.random.multivariate_normal([beta,beta], [[25,0],[0,1]],  nobs)
    return data[:,0],data[:,1],nobs

yn,xn,nobs = gen_data()
ll1,grad1,hess1,params1,ll2,grad2,hess2,params2 = setup_shi(yn,xn)
print(grad1.shape,hess1.shape)

(1000, 1) (1, 1)


# Ex 0

In [11]:
beta = 0

In [13]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Two-Step & Bootstrap & Shi (2015) \\ \hline \hline
No selection & 1.00 & 1.00 & 1.00 & 0.93   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.07   \\
\hline
\end{tabular}


llr:10.005957837991415, std:14.415226875998163
(array([1., 0., 0.]), array([1., 0., 0.]), array([1., 0., 0.]), array([0.93, 0.  , 0.07]), 10.005957837991415, 14.415226875998163, 18.59163378124725)


In [14]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Two-Step & Bootstrap & Shi (2015) \\ \hline \hline
No selection & 1.00 & 1.00 & 1.00 & 0.90   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.10   \\
\hline
\end{tabular}


llr:13.634619622358986, std:20.261859043232484
(array([1., 0., 0.]), array([1., 0., 0.]), array([1., 0., 0.]), array([0.9, 0. , 0.1]), 13.634619622358986, 20.261859043232484, 21.06417875014326)


In [15]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=1000, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Two-Step & Bootstrap & Shi (2015) \\ \hline \hline
No selection & 1.00 & 1.00 & 1.00 & 0.92   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.08   \\
\hline
\end{tabular}


llr:11.300949351914987, std:16.5645778557757
(array([1., 0., 0.]), array([1., 0., 0.]), array([1., 0., 0.]), array([0.92, 0.  , 0.08]), 11.300949351914987, 16.5645778557757, 19.630738015550214)


# Ex 0.5

In [16]:
beta = 0.5

In [17]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Two-Step & Bootstrap & Shi (2015) \\ \hline \hline
No selection & 0.88 & 0.88 & 1.00 & 0.93   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.12 & 0.12 & 0.00 & 0.07   \\
\hline
\end{tabular}


llr:12.238372178221207, std:41.817255593398464
(array([0.88, 0.  , 0.12]), array([0.88, 0.  , 0.12]), array([1., 0., 0.]), array([0.93, 0.  , 0.07]), 12.238372178221207, 41.817255593398464, 41.42787773885895)


In [18]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Two-Step & Bootstrap & Shi (2015) \\ \hline \hline
No selection & 0.85 & 0.85 & 1.00 & 0.95   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.15 & 0.15 & 0.00 & 0.05   \\
\hline
\end{tabular}


llr:8.2956816443247, std:61.76695528919151
(array([0.85, 0.  , 0.15]), array([0.85, 0.  , 0.15]), array([1., 0., 0.]), array([0.95, 0.  , 0.05]), 8.2956816443247, 61.76695528919151, 56.84555345874658)


In [19]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=1000, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Two-Step & Bootstrap & Shi (2015) \\ \hline \hline
No selection & 0.89 & 0.89 & 1.00 & 0.96   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.11 & 0.11 & 0.00 & 0.04   \\
\hline
\end{tabular}


llr:0.4633855312068816, std:78.71178621628826
(array([0.89, 0.  , 0.11]), array([0.89, 0.  , 0.11]), array([1., 0., 0.]), array([0.96, 0.  , 0.04]), 0.4633855312068816, 78.71178621628826, 77.75475984643913)


# Ex 1

In [20]:
beta = 1

In [ ]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

In [ ]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

In [ ]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=1000, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi)
vuong_tests4.print_mc(mc_out)
print(mc_out)

# Ex 1.5

In [ ]:
beta = 1.5

In [ ]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

In [ ]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

In [ ]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=1000, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi)
vuong_tests4.print_mc(mc_out)
print(mc_out)

# Ex 2

In [ ]:
beta = 2

In [ ]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

In [ ]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

In [ ]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=1000, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi)
vuong_tests4.print_mc(mc_out)
print(mc_out)