In [1]:
%load_ext autoreload
%autoreload 2

from statsmodels.base.model import GenericLikelihoodModel

import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import scipy.stats as stats
import sys

from scipy.stats import multivariate_normal

sys.path.append("../")
import vuong_tests4

In [2]:
class JointNormal1(GenericLikelihoodModel):
    
    def loglikeobs(self, params):
        data = np.concatenate([[self.endog],self.exog.transpose()],axis=0)
        mult_rv = stats.multivariate_normal([params[0], 0.0], [[1,0],[0,1]])
        return mult_rv.logpdf(data.transpose())
    
    
class JointNormal2(GenericLikelihoodModel):
    
    def loglikeobs(self, params):
        data = np.concatenate([[self.endog],self.exog.transpose()],axis=0)
        mult_rv = stats.multivariate_normal([0.0, params[0]], [[1,0],[0,1]])
        return mult_rv.logpdf(data.transpose())


def setup_shi(yn,xn,return_model=False):
    # model 1 grad, etc.
    nobs = yn.shape[0]
    model1_param = np.array([yn.mean()])
    model2_param = np.array([xn.mean()])
    
    model1_deriv = JointNormal1(yn,xn)
    ll1 = model1_deriv.loglikeobs(model1_param)
    grad1 =  model1_deriv.score_obs(model1_param).reshape( (nobs,1) )
    hess1 = model1_deriv.hessian(model1_param)
    
    
    model2_deriv = JointNormal2(yn,xn)
    ll2 = model2_deriv.loglikeobs(model2_param)
    grad2 =  model2_deriv.score_obs(model2_param).reshape( (nobs,1) )  
    hess2 = model2_deriv.hessian(model2_param)
    if return_model:
        return ll1,grad1,hess1,params1,model1_deriv,ll2,grad2,hess2,params2,model2_deriv
    return ll1,grad1,hess1,model1_param,ll2,grad2,hess2,model2_param

def gen_data(beta= 1.5, nobs=1000):
    cov = [[25, 0], [0, 1]]
    data = np.random.multivariate_normal([beta,beta], [[25,0],[0,1]],  nobs)
    return data[:,0],data[:,1],nobs

yn,xn,nobs = gen_data()
ll1,grad1,hess1,params1,ll2,grad2,hess2,params2 = setup_shi(yn,xn)
print(grad1.shape,hess1.shape)

(1000, 1) (1, 1)


# Ex 0

In [3]:
beta = 0

In [4]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Two-Step & Bootstrap & Shi (2015) \\ \hline \hline
No selection & 1.00 & 1.00 & 1.00 & 0.90   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.10   \\
\hline
\end{tabular}


llr:10.493526486617089, std:15.387942861203388
(array([1., 0., 0.]), array([1., 0., 0.]), array([1., 0., 0.]), array([0.9, 0. , 0.1]), 10.493526486617089, 15.387942861203388, 19.016552908451725)


In [5]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Two-Step & Bootstrap & Shi (2015) \\ \hline \hline
No selection & 1.00 & 1.00 & 1.00 & 0.93   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.07   \\
\hline
\end{tabular}


llr:12.360207058770513, std:15.537442687297562
(array([1., 0., 0.]), array([1., 0., 0.]), array([1., 0., 0.]), array([0.93, 0.  , 0.07]), 12.360207058770513, 15.537442687297562, 21.09209007574624)


In [6]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=1000, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Two-Step & Bootstrap & Shi (2015) \\ \hline \hline
No selection & 1.00 & 1.00 & 1.00 & 0.91   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.09   \\
\hline
\end{tabular}


llr:10.051846453750958, std:15.644447981471219
(array([1., 0., 0.]), array([1., 0., 0.]), array([1., 0., 0.]), array([0.91, 0.  , 0.09]), 10.051846453750958, 15.644447981471219, 18.080331514832814)


# Ex 0.5

In [7]:
beta = 0.5

In [8]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Two-Step & Bootstrap & Shi (2015) \\ \hline \hline
No selection & 0.83 & 0.99 & 1.00 & 0.91   \\
Model 1 & 0.01 & 0.01 & 0.00 & 0.00   \\
Model 2 & 0.16 & 0.00 & 0.00 & 0.09   \\
\hline
\end{tabular}


llr:9.996775597654574, std:45.25335964147784
(array([0.83, 0.01, 0.16]), array([0.99, 0.01, 0.  ]), array([1., 0., 0.]), array([0.91, 0.  , 0.09]), 9.996775597654574, 45.25335964147784, 40.922335217968374)


In [9]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Two-Step & Bootstrap & Shi (2015) \\ \hline \hline
No selection & 0.94 & 1.00 & 1.00 & 0.97   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.06 & 0.00 & 0.00 & 0.03   \\
\hline
\end{tabular}


llr:19.626350031191112, std:54.152663344330406
(array([0.94, 0.  , 0.06]), array([1., 0., 0.]), array([1., 0., 0.]), array([0.97, 0.  , 0.03]), 19.626350031191112, 54.152663344330406, 61.70511318699122)


In [10]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=1000, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Two-Step & Bootstrap & Shi (2015) \\ \hline \hline
No selection & 0.90 & 0.99 & 1.00 & 0.98   \\
Model 1 & 0.01 & 0.01 & 0.00 & 0.00   \\
Model 2 & 0.09 & 0.00 & 0.00 & 0.02   \\
\hline
\end{tabular}


llr:18.207280310205203, std:90.5152999801589
(array([0.9 , 0.01, 0.09]), array([0.99, 0.01, 0.  ]), array([1., 0., 0.]), array([0.98, 0.  , 0.02]), 18.207280310205203, 90.5152999801589, 82.35789451084094)


# Ex 1

In [11]:
beta = 1

In [12]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Two-Step & Bootstrap & Shi (2015) \\ \hline \hline
No selection & 0.94 & 0.99 & 1.00 & 0.98   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.06 & 0.01 & 0.00 & 0.02   \\
\hline
\end{tabular}


llr:18.811177058675995, std:77.7744630093317
(array([0.94, 0.  , 0.06]), array([0.99, 0.  , 0.01]), array([1., 0., 0.]), array([0.98, 0.  , 0.02]), 18.811177058675995, 77.7744630093317, 82.87445401728584)


In [13]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Two-Step & Bootstrap & Shi (2015) \\ \hline \hline
No selection & 0.94 & 0.94 & 1.00 & 1.00   \\
Model 1 & 0.01 & 0.01 & 0.00 & 0.00   \\
Model 2 & 0.05 & 0.05 & 0.00 & 0.00   \\
\hline
\end{tabular}


llr:8.300586033600814, std:110.38197651637573
(array([0.94, 0.01, 0.05]), array([0.94, 0.01, 0.05]), array([1., 0., 0.]), array([1., 0., 0.]), 8.300586033600814, 110.38197651637573, 111.8495744127915)


In [14]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=1000, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Two-Step & Bootstrap & Shi (2015) \\ \hline \hline
No selection & 0.93 & 0.93 & 1.00 & 0.98   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.07 & 0.07 & 0.00 & 0.02   \\
\hline
\end{tabular}


llr:-4.997412196642622, std:160.3470671368508
(array([0.93, 0.  , 0.07]), array([0.93, 0.  , 0.07]), array([1., 0., 0.]), array([0.98, 0.  , 0.02]), -4.997412196642622, 160.3470671368508, 159.76748127182702)


# Ex 1.5

In [15]:
beta = 1.5

In [16]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Two-Step & Bootstrap & Shi (2015) \\ \hline \hline
No selection & 0.93 & 0.93 & 1.00 & 1.00   \\
Model 1 & 0.02 & 0.02 & 0.00 & 0.00   \\
Model 2 & 0.05 & 0.05 & 0.00 & 0.00   \\
\hline
\end{tabular}


llr:9.137434117882206, std:122.41842490700289
(array([0.93, 0.02, 0.05]), array([0.93, 0.02, 0.05]), array([1., 0., 0.]), array([1., 0., 0.]), 9.137434117882206, 122.41842490700289, 120.38832823574371)


In [17]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Two-Step & Bootstrap & Shi (2015) \\ \hline \hline
No selection & 0.96 & 0.96 & 1.00 & 0.99   \\
Model 1 & 0.01 & 0.01 & 0.00 & 0.00   \\
Model 2 & 0.03 & 0.03 & 0.00 & 0.01   \\
\hline
\end{tabular}


llr:12.807575902860286, std:146.81578707598405
(array([0.96, 0.01, 0.03]), array([0.96, 0.01, 0.03]), array([1., 0., 0.]), array([0.99, 0.  , 0.01]), 12.807575902860286, 146.81578707598405, 170.44098374433102)


In [18]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=1000, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Two-Step & Bootstrap & Shi (2015) \\ \hline \hline
No selection & 0.97 & 0.97 & 1.00 & 1.00   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.03 & 0.03 & 0.00 & 0.00   \\
\hline
\end{tabular}


llr:-3.7224009454048974, std:232.0538782770864
(array([0.97, 0.  , 0.03]), array([0.97, 0.  , 0.03]), array([1., 0., 0.]), array([1., 0., 0.]), -3.7224009454048974, 232.0538782770864, 239.41067751074053)


# Ex 2

In [19]:
beta = 2

In [20]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Two-Step & Bootstrap & Shi (2015) \\ \hline \hline
No selection & 0.94 & 0.94 & 1.00 & 1.00   \\
Model 1 & 0.02 & 0.02 & 0.00 & 0.00   \\
Model 2 & 0.04 & 0.04 & 0.00 & 0.00   \\
\hline
\end{tabular}


llr:23.21901306513071, std:159.24808279122038
(array([0.94, 0.02, 0.04]), array([0.94, 0.02, 0.04]), array([1., 0., 0.]), array([1., 0., 0.]), 23.21901306513071, 159.24808279122038, 162.31714999098875)


In [21]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Two-Step & Bootstrap & Shi (2015) \\ \hline \hline
No selection & 0.94 & 0.94 & 1.00 & 1.00   \\
Model 1 & 0.03 & 0.03 & 0.00 & 0.00   \\
Model 2 & 0.03 & 0.03 & 0.00 & 0.00   \\
\hline
\end{tabular}


llr:29.4809449866916, std:229.2634195787716
(array([0.94, 0.03, 0.03]), array([0.94, 0.03, 0.03]), array([1., 0., 0.]), array([1., 0., 0.]), 29.4809449866916, 229.2634195787716, 229.7053938003738)


In [22]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=1000, beta =beta)
mc_out = vuong_tests4.monte_carlo(100,gen_data_ex,setup_shi)
vuong_tests4.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|}
\hline
Model &  Normal & Two-Step & Bootstrap & Shi (2015) \\ \hline \hline
No selection & 0.93 & 0.93 & 1.00 & 1.00   \\
Model 1 & 0.02 & 0.02 & 0.00 & 0.00   \\
Model 2 & 0.05 & 0.05 & 0.00 & 0.00   \\
\hline
\end{tabular}


llr:26.60654367549042, std:356.1270109195467
(array([0.93, 0.02, 0.05]), array([0.93, 0.02, 0.05]), array([1., 0., 0.]), array([1., 0., 0.]), 26.60654367549042, 356.1270109195467, 323.59758140825187)
