In [5]:
%load_ext autoreload
%autoreload 2

from statsmodels.base.model import GenericLikelihoodModel

import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import scipy.stats as stats
import sys

from scipy.stats import multivariate_normal

sys.path.append("../")
import vuong_tests5

In [6]:
class JointNormal1(GenericLikelihoodModel):
    
    def loglikeobs(self, params):
        data = np.concatenate([[self.endog],self.exog.transpose()],axis=0)
        mult_rv = stats.multivariate_normal([params[0], 0.0], [[1,0],[0,1]])
        return mult_rv.logpdf(data.transpose())
    
    
class JointNormal2(GenericLikelihoodModel):
    
    def loglikeobs(self, params):
        data = np.concatenate([[self.endog],self.exog.transpose()],axis=0)
        mult_rv = stats.multivariate_normal([0.0, params[0]], [[1,0],[0,1]])
        return mult_rv.logpdf(data.transpose())


def setup_shi(yn,xn):
    # model 1 grad, etc.
    nobs = yn.shape[0]
    model1_param = np.array([yn.mean()])
    model2_param = np.array([xn.mean()])
    
    model1_deriv = JointNormal1(yn,xn)
    ll1 = model1_deriv.loglikeobs(model1_param)
    grad1 =  model1_deriv.score_obs(model1_param).reshape( (nobs,1) )
    hess1 = model1_deriv.hessian(model1_param)
    
    
    model2_deriv = JointNormal2(yn,xn)
    ll2 = model2_deriv.loglikeobs(model2_param)
    grad2 =  model2_deriv.score_obs(model2_param).reshape( (nobs,1) )  
    hess2 = model2_deriv.hessian(model2_param)
    
    return ll1,grad1,hess1,model1_param,ll2,grad2,hess2,model2_param

def gen_data(beta= 1.5, nobs=1000):
    cov = [[25, 0], [0, 1]]
    data = np.random.multivariate_normal([beta,beta], [[25,0],[0,1]],  nobs)
    return data[:,0],data[:,1],nobs

yn,xn,nobs = gen_data()
ll1,grad1,hess1,params1,ll2,grad2,hess2,params2 = setup_shi(yn,xn)
print(grad1.shape,hess1.shape)

(1000, 1) (1, 1)


# Ex 0

In [7]:
beta = 0

In [8]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, beta =beta)
mc_out = vuong_tests5.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 1.00 & 0.82 & 0.80 & 0.81 & 0.98   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.00 & 0.18 & 0.20 & 0.19 & 0.02   \\
\hline
\end{tabular}
(array([1., 0., 0.]), array([0.82, 0.  , 0.18]), array([0.8, 0. , 0.2]), array([0.81, 0.  , 0.19]), array([0.98, 0.  , 0.02]), 13.200707342995845, 18.19089732461717, 21.220072415220773)


In [9]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, beta =beta)
mc_out = vuong_tests5.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 1.00 & 0.77 & 0.79 & 0.76 & 0.89   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.00 & 0.23 & 0.21 & 0.24 & 0.11   \\
\hline
\end{tabular}
(array([1., 0., 0.]), array([0.77, 0.  , 0.23]), array([0.79, 0.  , 0.21]), array([0.76, 0.  , 0.24]), array([0.89, 0.  , 0.11]), 11.363248249764684, 14.394576191933664, 19.49378608758709)


In [10]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=1000, beta =beta)
mc_out = vuong_tests5.monte_carlo(100,gen_data_ex,setup_shi)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 1.00 & 0.76 & 0.76 & 0.77 & 0.93   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.00 & 0.24 & 0.24 & 0.23 & 0.07   \\
\hline
\end{tabular}
(array([1., 0., 0.]), array([0.76, 0.  , 0.24]), array([0.76, 0.  , 0.24]), array([0.77, 0.  , 0.23]), array([0.93, 0.  , 0.07]), 11.632262454659026, 16.357243526226586, 19.698788501772544)


# Ex 1

In [3]:
beta = 1

In [4]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, beta =beta)
mc_out = vuong_tests5.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.95 & 0.91 & 0.91 & 0.91 & 0.99   \\
Model 1 & 0.01 & 0.01 & 0.01 & 0.01 & 0.00   \\
Model 2 & 0.04 & 0.08 & 0.08 & 0.08 & 0.01   \\
\hline
\end{tabular}
(array([0.95, 0.01, 0.04]), array([0.91, 0.01, 0.08]), array([0.91, 0.01, 0.08]), array([0.91, 0.01, 0.08]), array([0.99, 0.  , 0.01]), 15.29624301556337, 85.60420522317551, 81.76129158512427)


In [5]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, beta =beta)
mc_out = vuong_tests5.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.89 & 0.87 & 0.88 & 0.87 & 1.00   \\
Model 1 & 0.04 & 0.04 & 0.02 & 0.04 & 0.00   \\
Model 2 & 0.07 & 0.09 & 0.10 & 0.09 & 0.00   \\
\hline
\end{tabular}
(array([0.89, 0.04, 0.07]), array([0.87, 0.04, 0.09]), array([0.88, 0.02, 0.1 ]), array([0.87, 0.04, 0.09]), array([1., 0., 0.]), 15.308466367382366, 132.545927580924, 114.60972710434947)


In [6]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=1000, beta =beta)
mc_out = vuong_tests5.monte_carlo(100,gen_data_ex,setup_shi)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.96 & 0.95 & 0.95 & 0.96 & 1.00   \\
Model 1 & 0.02 & 0.02 & 0.02 & 0.02 & 0.00   \\
Model 2 & 0.02 & 0.03 & 0.03 & 0.02 & 0.00   \\
\hline
\end{tabular}
(array([0.96, 0.02, 0.02]), array([0.95, 0.02, 0.03]), array([0.95, 0.02, 0.03]), array([0.96, 0.02, 0.02]), array([1., 0., 0.]), 29.3448127995169, 150.59091234454237, 164.15252699668474)


# Ex 2

In [7]:
beta = 1.5

In [8]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, beta =beta)
mc_out = vuong_tests5.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.93 & 0.93 & 0.91 & 0.91 & 0.99   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.07 & 0.07 & 0.09 & 0.09 & 0.01   \\
\hline
\end{tabular}
(array([0.93, 0.  , 0.07]), array([0.93, 0.  , 0.07]), array([0.91, 0.  , 0.09]), array([0.91, 0.  , 0.09]), array([0.99, 0.  , 0.01]), -5.736084111924682, 106.45743151709708, 119.0424725946626)


In [9]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, beta =beta)
mc_out = vuong_tests5.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.96 & 0.97 & 0.95 & 0.92 & 1.00   \\
Model 1 & 0.02 & 0.02 & 0.03 & 0.04 & 0.00   \\
Model 2 & 0.02 & 0.01 & 0.02 & 0.04 & 0.00   \\
\hline
\end{tabular}
(array([0.96, 0.02, 0.02]), array([0.97, 0.02, 0.01]), array([0.95, 0.03, 0.02]), array([0.92, 0.04, 0.04]), array([1., 0., 0.]), 49.59118749619935, 188.29179060193604, 176.70297586348536)


In [10]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=1000, beta =beta)
mc_out = vuong_tests5.monte_carlo(100,gen_data_ex,setup_shi)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.92 & 0.92 & 0.93 & 0.92 & 1.00   \\
Model 1 & 0.03 & 0.03 & 0.02 & 0.03 & 0.00   \\
Model 2 & 0.05 & 0.05 & 0.05 & 0.05 & 0.00   \\
\hline
\end{tabular}
(array([0.92, 0.03, 0.05]), array([0.92, 0.03, 0.05]), array([0.93, 0.02, 0.05]), array([0.92, 0.03, 0.05]), array([1., 0., 0.]), 8.080287011628094, 261.10368774590097, 240.7502580561804)


# Ex 3

In [11]:
beta = 2

In [12]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, beta =beta)
mc_out = vuong_tests5.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.91 & 0.91 & 0.91 & 0.91 & 1.00   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.09 & 0.09 & 0.09 & 0.09 & 0.00   \\
\hline
\end{tabular}
(array([0.91, 0.  , 0.09]), array([0.91, 0.  , 0.09]), array([0.91, 0.  , 0.09]), array([0.91, 0.  , 0.09]), array([1., 0., 0.]), 8.958844857747824, 157.28894847360112, 160.59668819473177)


In [13]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, beta =beta)
mc_out = vuong_tests5.monte_carlo(100,gen_data_ex,setup_shi,trials=100)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.92 & 0.87 & 0.89 & 0.90 & 1.00   \\
Model 1 & 0.04 & 0.04 & 0.04 & 0.04 & 0.00   \\
Model 2 & 0.04 & 0.09 & 0.07 & 0.06 & 0.00   \\
\hline
\end{tabular}
(array([0.92, 0.04, 0.04]), array([0.87, 0.04, 0.09]), array([0.89, 0.04, 0.07]), array([0.9 , 0.04, 0.06]), array([1., 0., 0.]), 13.93455695917987, 241.10651330658683, 227.7575476892359)


In [14]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=1000, beta =beta)
mc_out = vuong_tests5.monte_carlo(100,gen_data_ex,setup_shi)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.95 & 0.95 & 0.94 & 0.95 & 1.00   \\
Model 1 & 0.03 & 0.03 & 0.02 & 0.03 & 0.00   \\
Model 2 & 0.02 & 0.02 & 0.04 & 0.02 & 0.00   \\
\hline
\end{tabular}
(array([0.95, 0.03, 0.02]), array([0.95, 0.03, 0.02]), array([0.94, 0.02, 0.04]), array([0.95, 0.03, 0.02]), array([1., 0., 0.]), 10.415811333310808, 343.90031066544765, 321.82343685008766)


In [ ]:
beta = 3