In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from statsmodels.base.model import GenericLikelihoodModel
import scipy.stats as stats
import sys

sys.path.append("../")
import vuong_tests5

In [2]:
class OLS_loglike(GenericLikelihoodModel):
    
    def __init__(self, *args,ols=False, **kwargs):
        super(OLS_loglike,self).__init__(*args,**kwargs)
        self.ols = ols

    def loglikeobs(self, params):
        y = self.endog
        x = self.exog
        mu_y = np.matmul(x,params)  
        resid = y - mu_y
        sigma = np.sqrt(np.sum(resid**2)/resid.shape[0])
        pr_y = stats.norm.logpdf( resid, loc=0,scale=sigma )
        return pr_y


def setup_shi(yn,xn,return_model=False,num_params=4):
    x1n,x2n = xn[:,0],xn[:,1:num_params]
    
    # model 1 grad, etc.
    model1 = sm.OLS(yn,sm.add_constant(x1n))
    model1_fit = model1.fit(disp=False)
    params1 = (model1_fit.params)
    
    model1_deriv = OLS_loglike(yn,sm.add_constant(x1n))
    ll1 = model1_deriv.loglikeobs(model1_fit.params)
    grad1 =  model1_deriv.score_obs(model1_fit.params)    
    hess1 = model1_deriv.hessian(model1_fit.params)
    
    #model 2 grad, etc.
    model2 = sm.OLS(yn,sm.add_constant(x2n))
    model2_fit = model2.fit(disp=False)
    params2 = (model2_fit.params)
    
    model2_deriv = OLS_loglike(yn,sm.add_constant(x2n))
    ll2 = model2_deriv.loglikeobs(model2_fit.params)
    grad2 =  model2_deriv.score_obs(model2_fit.params)    
    hess2 = model2_deriv.hessian(model2_fit.params)
    
    if return_model:
        return ll1,grad1,hess1,params1,model1,ll2,grad2,hess2,params2,model2
    return ll1,grad1,hess1,params1,ll2,grad2,hess2,params2

def gen_data(nobs=1000, a=0.25, num_params=4):
    x = np.random.normal(scale=1., size=(nobs,1+num_params))
    e = np.random.normal(loc=0.0, scale=1.0, size=nobs)
    y = 1 + a*x[:,0] + a/np.sqrt(num_params)*x[:,1:num_params].sum(axis=1) + e
    return y,x,nobs

yn,xn,nobs = gen_data()
ll1,grad1,hess1,params1,ll2,grad2,hess2,params2 = setup_shi(yn,xn,return_model=False,num_params=15)

# a  = .25, k= 4, something is not right...

In [3]:
a = 0.25
num_params=4
num_sims = 100

In [4]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, a=a,  num_params=num_params)
mc_out = vuong_tests5.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.98 & 0.98 & 0.98 & 0.98 & 1.00   \\
Model 1 & 0.01 & 0.01 & 0.01 & 0.02 & 0.00   \\
Model 2 & 0.01 & 0.01 & 0.01 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.98, 0.01, 0.01]), array([0.98, 0.01, 0.01]), array([0.98, 0.01, 0.01]), array([0.98, 0.02, 0.  ]), array([1., 0., 0.]), 0.8798555202508876, 4.603170364020201, 5.082958107018467)


In [5]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, a=a,  num_params=num_params)
mc_out = vuong_tests5.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.91 & 0.91 & 0.91 & 0.92 & 0.96   \\
Model 1 & 0.09 & 0.09 & 0.09 & 0.08 & 0.04   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.91, 0.09, 0.  ]), array([0.91, 0.09, 0.  ]), array([0.91, 0.09, 0.  ]), array([0.92, 0.08, 0.  ]), array([0.96, 0.04, 0.  ]), 3.025271625981256, 7.105226534988547, 7.283411720918553)


# a  = .25, k= 9

In [6]:
a = 0.25
num_params=9
num_sims = 100

In [7]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, a=a,  num_params=num_params)
mc_out = vuong_tests5.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.96 & 0.95 & 0.95 & 0.95 & 0.96   \\
Model 1 & 0.03 & 0.03 & 0.04 & 0.04 & 0.03   \\
Model 2 & 0.01 & 0.02 & 0.01 & 0.01 & 0.01   \\
\hline
\end{tabular}
(array([0.96, 0.03, 0.01]), array([0.95, 0.03, 0.02]), array([0.95, 0.04, 0.01]), array([0.95, 0.04, 0.01]), array([0.96, 0.03, 0.01]), -2.6219648570229435, 5.673203753120052, 5.7536024541009825)


In [8]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, a=a,  num_params=num_params)
mc_out = vuong_tests5.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.93 & 0.91 & 0.94 & 0.92 & 0.95   \\
Model 1 & 0.05 & 0.07 & 0.04 & 0.06 & 0.03   \\
Model 2 & 0.02 & 0.02 & 0.02 & 0.02 & 0.02   \\
\hline
\end{tabular}
(array([0.93, 0.05, 0.02]), array([0.91, 0.07, 0.02]), array([0.94, 0.04, 0.02]), array([0.92, 0.06, 0.02]), array([0.95, 0.03, 0.02]), -2.0803214496683937, 8.29373606454768, 7.824439942139422)


In [9]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=100, a=a,  num_params=num_params)
mc_out = vuong_tests5.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.93 & 0.93 & 0.92 & 0.95 & 0.96   \\
Model 1 & 0.04 & 0.05 & 0.05 & 0.03 & 0.04   \\
Model 2 & 0.03 & 0.02 & 0.03 & 0.02 & 0.00   \\
\hline
\end{tabular}
(array([0.93, 0.04, 0.03]), array([0.93, 0.05, 0.02]), array([0.92, 0.05, 0.03]), array([0.95, 0.03, 0.02]), array([0.96, 0.04, 0.  ]), -4.238054932013599, 4.64108451002556, 4.256612245840278)


# a  = 0, k= 9

In [9]:
a = 0.00 
num_params=9
num_sims = 100

In [10]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, a=a,  num_params=num_params)
mc_out = vuong_tests5.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.99 & 0.99 & 1.00 & 0.99 & 0.99   \\
Model 1 & 0.01 & 0.01 & 0.00 & 0.01 & 0.01   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.99, 0.01, 0.  ]), array([0.99, 0.01, 0.  ]), array([1., 0., 0.]), array([0.99, 0.01, 0.  ]), array([0.99, 0.01, 0.  ]), -3.7197442007508323, 2.2795555263492253, 2.936440531685852)


In [11]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, a=a,  num_params=num_params)
mc_out = vuong_tests5.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.99 & 0.99 & 0.99 & 0.99 & 0.99   \\
Model 1 & 0.01 & 0.01 & 0.01 & 0.01 & 0.01   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.99, 0.01, 0.  ]), array([0.99, 0.01, 0.  ]), array([0.99, 0.01, 0.  ]), array([0.99, 0.01, 0.  ]), array([0.99, 0.01, 0.  ]), -3.483640684176712, 2.0516972974358763, 2.9040885234449245)


# a  = .25

In [12]:
a = 0.25
num_params=19
num_sims = 100

In [13]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, a=a,  num_params=num_params)
mc_out = vuong_tests5.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.95 & 0.95 & 0.95 & 0.95 & 0.95   \\
Model 1 & 0.03 & 0.03 & 0.03 & 0.03 & 0.03   \\
Model 2 & 0.02 & 0.02 & 0.02 & 0.02 & 0.02   \\
\hline
\end{tabular}
(array([0.95, 0.03, 0.02]), array([0.95, 0.03, 0.02]), array([0.95, 0.03, 0.02]), array([0.95, 0.03, 0.02]), array([0.95, 0.03, 0.02]), -8.773246729898304, 6.4729482879685785, 6.593554037487445)


In [14]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, a=a,  num_params=num_params)
mc_out = vuong_tests5.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.97 & 0.95 & 0.93 & 0.96 & 0.97   \\
Model 1 & 0.01 & 0.01 & 0.03 & 0.01 & 0.01   \\
Model 2 & 0.02 & 0.04 & 0.04 & 0.03 & 0.02   \\
\hline
\end{tabular}
(array([0.97, 0.01, 0.02]), array([0.95, 0.01, 0.04]), array([0.93, 0.03, 0.04]), array([0.96, 0.01, 0.03]), array([0.97, 0.01, 0.02]), -8.981645430942272, 8.109687350934205, 8.265751333322894)


In [15]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=1000, a=a,  num_params=num_params)
mc_out = vuong_tests5.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.92 & 0.93 & 0.90 & 0.91 & 0.93   \\
Model 1 & 0.06 & 0.05 & 0.06 & 0.06 & 0.06   \\
Model 2 & 0.02 & 0.02 & 0.04 & 0.03 & 0.01   \\
\hline
\end{tabular}
(array([0.92, 0.06, 0.02]), array([0.93, 0.05, 0.02]), array([0.9 , 0.06, 0.04]), array([0.91, 0.06, 0.03]), array([0.93, 0.06, 0.01]), -6.739603738840657, 12.768050787988567, 11.124473135869243)


# a = 0

In [16]:
a = 0.0
num_params=19
num_sims = 100

In [17]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, a=a,  num_params=num_params)
mc_out = vuong_tests5.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.98 & 0.98 & 0.97 & 0.98 & 0.99   \\
Model 1 & 0.02 & 0.02 & 0.03 & 0.02 & 0.01   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.98, 0.02, 0.  ]), array([0.98, 0.02, 0.  ]), array([0.97, 0.03, 0.  ]), array([0.98, 0.02, 0.  ]), array([0.99, 0.01, 0.  ]), -8.588703132093247, 3.0445125513897366, 4.269061424957786)


In [18]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, a=a,  num_params=num_params)
mc_out = vuong_tests5.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 1.00 & 1.00 & 1.00 & 0.99 & 1.00   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.01 & 0.00   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([1., 0., 0.]), array([1., 0., 0.]), array([1., 0., 0.]), array([0.99, 0.01, 0.  ]), array([1., 0., 0.]), -8.544728096987173, 3.6246609587803564, 4.328876391626203)


# evidence of power

In [19]:
a1,a2 = np.sqrt(1.09-1), 0.00
num_params= 9
num_sims = 100

def gen_data2(nobs=1000, a1=np.sqrt(1.09-1), a2=0.00 , num_params=19):
    x = np.random.normal(scale=1., size=(nobs,1+num_params))
    e = np.random.normal(loc=0.0, scale=1.0, size=nobs)
    y = 1 + a1*x[:,0] + a2/np.sqrt(num_params)*x[:,1:num_params].sum(axis=1) + e
    return y,x,nobs

In [20]:
a1,a2 = np.sqrt(1.09-1), 0.00
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data2(nobs=250, a1=a1, a2=a2, num_params=num_params)
mc_out = vuong_tests5.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.45 & 0.45 & 0.45 & 0.40 & 0.51   \\
Model 1 & 0.55 & 0.55 & 0.55 & 0.60 & 0.49   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.45, 0.55, 0.  ]), array([0.45, 0.55, 0.  ]), array([0.45, 0.55, 0.  ]), array([0.4, 0.6, 0. ]), array([0.51, 0.49, 0.  ]), 7.191813664339403, 5.094217705077527, 5.1885166789126105)


In [21]:
a1,a2 = np.sqrt(1.09**.5-1), 0.00
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data2(nobs=500, a1=a1, a2=a2, num_params=num_params)
mc_out = vuong_tests5.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.48 & 0.47 & 0.48 & 0.44 & 0.53   \\
Model 1 & 0.52 & 0.53 & 0.52 & 0.56 & 0.47   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.48, 0.52, 0.  ]), array([0.47, 0.53, 0.  ]), array([0.48, 0.52, 0.  ]), array([0.44, 0.56, 0.  ]), array([0.53, 0.47, 0.  ]), 7.2835610966807245, 5.191721469498081, 5.424192832926418)


In [22]:
a1,a2 = 0.00,np.sqrt(1.09-1)
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data2(nobs=250, a1=a1, a2=a2, num_params=num_params)
mc_out = vuong_tests5.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.51 & 0.49 & 0.51 & 0.49 & 0.62   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.49 & 0.51 & 0.49 & 0.51 & 0.38   \\
\hline
\end{tabular}
(array([0.51, 0.  , 0.49]), array([0.49, 0.  , 0.51]), array([0.51, 0.  , 0.49]), array([0.49, 0.  , 0.51]), array([0.62, 0.  , 0.38]), -14.213031199856093, 5.819169531396069, 5.205608301970684)


In [23]:
a1,a2 =  0.00,np.sqrt(1.09**.5-1)
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data2(nobs=500, a1=a1, a2=a2, num_params=num_params)
mc_out = vuong_tests5.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.54 & 0.56 & 0.51 & 0.51 & 0.58   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.46 & 0.44 & 0.49 & 0.49 & 0.42   \\
\hline
\end{tabular}
(array([0.54, 0.  , 0.46]), array([0.56, 0.  , 0.44]), array([0.51, 0.  , 0.49]), array([0.51, 0.  , 0.49]), array([0.58, 0.  , 0.42]), -13.569542451255797, 4.400747294594443, 5.297594067113448)
