In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import scipy.stats as stats
import sys

sys.path.append("../")
import vuong_tests5

In [2]:
def compute_loglike(resid):
    sigma = np.sqrt(np.sum(resid**2)/resid.shape[0])
    ll = np.log(stats.norm.pdf(resid,loc=0,scale=sigma))
    return ll

def compute_score(yn,xn,params):
    
    xn = sm.add_constant(xn)
    resid = yn - np.matmul(xn,params)
    
    k = len(params)
    scale = (resid**2).mean()
    
    tile_resid = np.tile( resid, k)
    tile_resid = np.reshape(tile_resid, (k,xn.shape[0]) ).transpose()
    grad = tile_resid*xn/scale     
    return grad
    
def compute_hess(yn,xn,params):
    pass


def setup_shi(yn,xn,return_model=False,num_params=15):
    x1n,x2n = xn[:,0],xn[:,1:num_params]
    
    # model 1 grad, etc.
    model1 = sm.OLS(yn,sm.add_constant(x1n))
    model1_fit = model1.fit(disp=False)
    params1 = (model1_fit.params)
    
    ll1 = compute_loglike(model1_fit.resid)
    grad1 =  compute_score(yn,x1n,model1_fit.params)
    hess1 = model1.hessian(model1_fit.params)
    
    #model 2 grad, etc.
    model2 = sm.OLS(yn,sm.add_constant(x2n))
    model2_fit = model2.fit(disp=False)
    params2 = (model2_fit.params)
    
    ll2 = compute_loglike(model2_fit.resid)
    grad2 =  compute_score(yn,x2n,model2_fit.params)
    hess2 = model2.hessian(model2_fit.params)
    
    if return_model:
        return ll1,grad1,hess1,params1,model1,ll2,grad2,hess2,params2,model2
    return ll1,grad1,hess1,params1,ll2,grad2,hess2,params2


# a  = .25

In [3]:
def gen_data(nobs=100, a=0.25, num_params=15):
    x = np.random.normal(scale=3., size=(nobs,1+num_params))
    e = np.random.normal(loc=0.0, scale=1.0, size=nobs)
    y = 1 + a*x[:,0] + a/np.sqrt(num_params)*x[:,1:num_params].sum(axis=1) + e
    return y,x,nobs

gen_data_ex = lambda : gen_data(nobs=1000, a=0.25, num_params=15)
mc_out = vuong_tests5.monte_carlo(1000,gen_data_ex,setup_shi)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.89 & 0.89 & 0.89 & 0.89 & 0.89   \\
Model 1 & 0.11 & 0.11 & 0.11 & 0.11 & 0.10   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.888, 0.109, 0.003]), array([0.888, 0.109, 0.003]), array([0.887, 0.11 , 0.003]), array([0.887, 0.11 , 0.003]), array([0.894, 0.103, 0.003]), 4.910366059975789, 24.01065730368641, 24.159843279508596)


In [4]:
gen_data_ex = lambda : gen_data(nobs=500, a=0.25, num_params=15)
mc_out = vuong_tests5.monte_carlo(1000,gen_data_ex,setup_shi)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.86 & 0.86 & 0.85 & 0.86 & 0.88   \\
Model 1 & 0.13 & 0.14 & 0.14 & 0.13 & 0.12   \\
Model 2 & 0.01 & 0.01 & 0.01 & 0.01 & 0.00   \\
\hline
\end{tabular}
(array([0.864, 0.129, 0.007]), array([0.856, 0.137, 0.007]), array([0.852, 0.142, 0.006]), array([0.862, 0.132, 0.006]), array([0.878, 0.117, 0.005]), -0.07685952229025227, 17.960533011436404, 17.139179388787355)


In [5]:
gen_data_ex = lambda : gen_data(nobs=250, a=0.25, num_params=15)
mc_out = vuong_tests5.monte_carlo(1000,gen_data_ex,setup_shi)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.88 & 0.87 & 0.86 & 0.87 & 0.89   \\
Model 1 & 0.12 & 0.13 & 0.13 & 0.13 & 0.11   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.876, 0.123, 0.001]), array([0.87 , 0.128, 0.002]), array([0.864, 0.133, 0.003]), array([0.869, 0.128, 0.003]), array([0.89 , 0.109, 0.001]), -3.326781452133483, 12.32899104043231, 12.164059458382232)


# a  = .125

In [6]:
gen_data_ex = lambda : gen_data(nobs=1000, a=0.125, num_params=15)
mc_out = vuong_tests5.monte_carlo(1000,gen_data_ex,setup_shi,trials=100)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.89 & 0.87 & 0.86 & 0.86 & 0.90   \\
Model 1 & 0.10 & 0.12 & 0.13 & 0.14 & 0.10   \\
Model 2 & 0.00 & 0.01 & 0.01 & 0.01 & 0.00   \\
\hline
\end{tabular}
(array([0.892, 0.103, 0.005]), array([0.87 , 0.124, 0.006]), array([0.861, 0.133, 0.006]), array([0.859, 0.135, 0.006]), array([0.9  , 0.097, 0.003]), -2.693697222052389, 15.632882361149566, 15.30402512595683)


In [7]:
gen_data_ex = lambda : gen_data(nobs=500, a=0.125, num_params=15)
mc_out = vuong_tests5.monte_carlo(1000,gen_data_ex,setup_shi,trials=100)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.88 & 0.87 & 0.87 & 0.86 & 0.90   \\
Model 1 & 0.11 & 0.13 & 0.13 & 0.13 & 0.10   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.01 & 0.00   \\
\hline
\end{tabular}
(array([0.883, 0.114, 0.003]), array([0.866, 0.13 , 0.004]), array([0.87 , 0.128, 0.002]), array([0.861, 0.133, 0.006]), array([0.895, 0.102, 0.003]), -4.585908719001391, 10.780486076789439, 11.029309945080486)


In [8]:
gen_data_ex = lambda : gen_data(nobs=250, a=0.125, num_params=15)
mc_out = vuong_tests5.monte_carlo(1000,gen_data_ex,setup_shi)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.86 & 0.86 & 0.86 & 0.86 & 0.88   \\
Model 1 & 0.14 & 0.14 & 0.14 & 0.14 & 0.12   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.857, 0.142, 0.001]), array([0.856, 0.143, 0.001]), array([0.861, 0.139, 0.   ]), array([0.856, 0.143, 0.001]), array([0.878, 0.121, 0.001]), -5.453706864217157, 7.914410978443378, 8.139167218857299)


# a = 0

In [9]:
gen_data_ex = lambda : gen_data(nobs=1000, a=0.0, num_params=15)
mc_out = vuong_tests5.monte_carlo(1000,gen_data_ex,setup_shi)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.57 & 0.57 & 0.55 & 0.56 & 0.58   \\
Model 1 & 0.43 & 0.43 & 0.45 & 0.44 & 0.42   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.568, 0.432, 0.   ]), array([0.57, 0.43, 0.  ]), array([0.554, 0.446, 0.   ]), array([0.564, 0.436, 0.   ]), array([0.584, 0.416, 0.   ]), -6.7286497074735925, 2.9451274948656017, 3.83944273960237)


In [10]:
gen_data_ex = lambda : gen_data(nobs=500, a=0.0, num_params=15)
mc_out = vuong_tests5.monte_carlo(1000,gen_data_ex,setup_shi)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.58 & 0.56 & 0.56 & 0.56 & 0.60   \\
Model 1 & 0.42 & 0.44 & 0.44 & 0.44 & 0.40   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.576, 0.424, 0.   ]), array([0.562, 0.438, 0.   ]), array([0.56, 0.44, 0.  ]), array([0.563, 0.437, 0.   ]), array([0.602, 0.398, 0.   ]), -6.629773992340382, 2.757075334010902, 3.800478113454449)


In [11]:
gen_data_ex = lambda : gen_data(nobs=250, a=0.0, num_params=15)
mc_out = vuong_tests5.monte_carlo(1000,gen_data_ex,setup_shi)
vuong_tests5.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.58 & 0.58 & 0.56 & 0.57 & 0.61   \\
Model 1 & 0.42 & 0.42 & 0.44 & 0.43 & 0.39   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.58, 0.42, 0.  ]), array([0.578, 0.422, 0.   ]), array([0.562, 0.438, 0.   ]), array([0.566, 0.434, 0.   ]), array([0.614, 0.386, 0.   ]), -6.64836087160991, 2.7550177588527376, 3.774882183207644)


# other weird DGPs

In [ ]:
def gen_data(beta=0):
    nobs = 250
    #x = np.random.normal(low=-3., high=3., size=(nobs,3))
    x = np.random.normal(scale=3., size=(nobs,4))
    e = np.random.normal(loc=0.0, scale=1.0, size=nobs)
    y = 1 + 1/np.sqrt(2)*x[:,3] + 1/np.sqrt(2)*x[:,2] + 1*x[:,0] + beta * x[:,1] + e
    return y,x,nobs

yn,xn,nobs = gen_data()
ll1,grad1,hess1,ll2,k1, grad2,hess2,k2 = setup_shi(yn,xn)


mc_out = vuong_tests5.monte_carlo(1000,gen_data,setup_shi)
vuong_tests5.print_mc(mc_out)