In [7]:
%load_ext autoreload
%autoreload 2

import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from statsmodels.base.model import GenericLikelihoodModel
import scipy.stats as stats
import sys

sys.path.append("../")
import vuong_tests3

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [8]:
class OLS_loglike(GenericLikelihoodModel):
    
    def __init__(self, *args,ols=False, **kwargs):
        super(OLS_loglike,self).__init__(*args,**kwargs)
        self.ols = ols

    def loglikeobs(self, params):
        y = self.endog
        x = self.exog
        mu_y = np.matmul(x,params)  
        resid = y - mu_y
        sigma = np.sqrt(np.sum(resid**2)/resid.shape[0])
        pr_y = stats.norm.logpdf( resid, loc=0,scale=sigma )
        return pr_y


def setup_shi(yn,xn,return_model=False,num_params=4):
    x1n,x2n = xn[:,0],xn[:,1:num_params]
    
    # model 1 grad, etc.
    model1 = sm.OLS(yn,sm.add_constant(x1n))
    model1_fit = model1.fit(disp=False)
    params1 = (model1_fit.params)
    
    model1_deriv = OLS_loglike(yn,sm.add_constant(x1n))
    ll1 = model1_deriv.loglikeobs(model1_fit.params)
    grad1 =  model1_deriv.score_obs(model1_fit.params)    
    hess1 = model1_deriv.hessian(model1_fit.params)
    
    #model 2 grad, etc.
    model2 = sm.OLS(yn,sm.add_constant(x2n))
    model2_fit = model2.fit(disp=False)
    params2 = (model2_fit.params)
    
    model2_deriv = OLS_loglike(yn,sm.add_constant(x2n))
    ll2 = model2_deriv.loglikeobs(model2_fit.params)
    grad2 =  model2_deriv.score_obs(model2_fit.params)    
    hess2 = model2_deriv.hessian(model2_fit.params)
    
    if return_model:
        return ll1,grad1,hess1,params1,model1,ll2,grad2,hess2,params2,model2
    return ll1,grad1,hess1,params1,ll2,grad2,hess2,params2

def gen_data(nobs=1000, a=0.25, num_params=4):
    x = np.random.normal(scale=1., size=(nobs,1+num_params))
    e = np.random.normal(loc=0.0, scale=1.0, size=nobs)
    y = 1 + a*x[:,0] + a/np.sqrt(num_params)*x[:,1:num_params].sum(axis=1) + e
    return y,x,nobs

yn,xn,nobs = gen_data()
ll1,grad1,hess1,params1,ll2,grad2,hess2,params2 = setup_shi(yn,xn,return_model=False,num_params=15)

# a  = .25, k= 4, something is not right...

In [9]:
a = 0.25
num_params=4
num_sims = 100

In [10]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, a=a,  num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.97 & 0.97 & 0.95 & 0.97 & 0.98   \\
Model 1 & 0.02 & 0.02 & 0.05 & 0.03 & 0.02   \\
Model 2 & 0.01 & 0.01 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.97, 0.02, 0.01]), array([0.97, 0.02, 0.01]), array([0.95, 0.05, 0.  ]), array([0.97, 0.03, 0.  ]), array([0.98, 0.02, 0.  ]), 0.8631434606434919, 5.220764487515912, 5.3357771637994915)


In [11]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, a=a,  num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.98 & 0.97 & 0.96 & 0.97 & 0.98   \\
Model 1 & 0.02 & 0.03 & 0.04 & 0.03 & 0.02   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.98, 0.02, 0.  ]), array([0.97, 0.03, 0.  ]), array([0.96, 0.04, 0.  ]), array([0.97, 0.03, 0.  ]), array([0.98, 0.02, 0.  ]), 2.3404268441913225, 6.9876622384133, 7.282929932447111)


# a  = .25, k= 9

In [12]:
a = 0.25
num_params=9
num_sims = 100

In [13]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, a=a,  num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.99 & 0.98 & 0.97 & 0.98 & 0.99   \\
Model 1 & 0.01 & 0.02 & 0.03 & 0.02 & 0.01   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.99, 0.01, 0.  ]), array([0.98, 0.02, 0.  ]), array([0.97, 0.03, 0.  ]), array([0.98, 0.02, 0.  ]), array([0.99, 0.01, 0.  ]), -2.5990298645237186, 5.139456493794912, 5.761643525938734)


In [14]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, a=a,  num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.95 & 0.98 & 0.97 & 0.97 & 0.98   \\
Model 1 & 0.01 & 0.01 & 0.02 & 0.02 & 0.01   \\
Model 2 & 0.04 & 0.01 & 0.01 & 0.01 & 0.01   \\
\hline
\end{tabular}
(array([0.95, 0.01, 0.04]), array([0.98, 0.01, 0.01]), array([0.97, 0.02, 0.01]), array([0.97, 0.02, 0.01]), array([0.98, 0.01, 0.01]), -1.8938265055963261, 7.041774550195131, 7.6974827695809855)


# a  = 0, k= 9

In [15]:
a = 0.00 
num_params=9
num_sims = 100

In [16]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, a=a,  num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.96 & 0.99 & 1.00 & 1.00 & 1.00   \\
Model 1 & 0.00 & 0.01 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.04 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.96, 0.  , 0.04]), array([0.99, 0.01, 0.  ]), array([1., 0., 0.]), array([1., 0., 0.]), array([1., 0., 0.]), -3.2237398550549714, 2.132987719352339, 2.885274444430426)


In [17]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, a=a,  num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.97 & 0.99 & 1.00 & 0.99 & 1.00   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.03 & 0.01 & 0.00 & 0.01 & 0.00   \\
\hline
\end{tabular}
(array([0.97, 0.  , 0.03]), array([0.99, 0.  , 0.01]), array([1., 0., 0.]), array([0.99, 0.  , 0.01]), array([1., 0., 0.]), -3.6592524916940543, 2.116007878191721, 2.9606478274969943)


# a  = .25

In [18]:
a = 0.25
num_params=19
num_sims = 100

In [19]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, a=a,  num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.81 & 0.96 & 0.96 & 0.97 & 0.98   \\
Model 1 & 0.00 & 0.04 & 0.04 & 0.03 & 0.02   \\
Model 2 & 0.19 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.81, 0.  , 0.19]), array([0.96, 0.04, 0.  ]), array([0.96, 0.04, 0.  ]), array([0.97, 0.03, 0.  ]), array([0.98, 0.02, 0.  ]), -7.981525987787544, 5.896238053668959, 6.576356172997991)


In [20]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, a=a,  num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.82 & 0.93 & 0.93 & 0.92 & 0.94   \\
Model 1 & 0.00 & 0.04 & 0.04 & 0.05 & 0.03   \\
Model 2 & 0.18 & 0.03 & 0.03 & 0.03 & 0.03   \\
\hline
\end{tabular}
(array([0.82, 0.  , 0.18]), array([0.93, 0.04, 0.03]), array([0.93, 0.04, 0.03]), array([0.92, 0.05, 0.03]), array([0.94, 0.03, 0.03]), -7.253321080519141, 8.662916871993243, 8.418579642752547)


In [21]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=1000, a=a,  num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.92 & 0.97 & 0.97 & 0.93 & 0.97   \\
Model 1 & 0.01 & 0.03 & 0.03 & 0.06 & 0.03   \\
Model 2 & 0.07 & 0.00 & 0.00 & 0.01 & 0.00   \\
\hline
\end{tabular}
(array([0.92, 0.01, 0.07]), array([0.97, 0.03, 0.  ]), array([0.97, 0.03, 0.  ]), array([0.93, 0.06, 0.01]), array([0.97, 0.03, 0.  ]), -5.5760501592078855, 10.691924066451952, 11.24271192438781)


# a = 0

In [22]:
a = 0.0
num_params=19
num_sims = 100

In [23]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, a=a,  num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.44 & 0.98 & 0.99 & 0.99 & 0.99   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.56 & 0.02 & 0.01 & 0.01 & 0.01   \\
\hline
\end{tabular}
(array([0.44, 0.  , 0.56]), array([0.98, 0.  , 0.02]), array([0.99, 0.  , 0.01]), array([0.99, 0.  , 0.01]), array([0.99, 0.  , 0.01]), -8.751933867092905, 3.6647496100155297, 4.217534207547186)


In [24]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, a=a,  num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.48 & 0.97 & 0.97 & 0.97 & 0.98   \\
Model 1 & 0.00 & 0.03 & 0.03 & 0.03 & 0.02   \\
Model 2 & 0.52 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.48, 0.  , 0.52]), array([0.97, 0.03, 0.  ]), array([0.97, 0.03, 0.  ]), array([0.97, 0.03, 0.  ]), array([0.98, 0.02, 0.  ]), -8.738341943572912, 3.3725840980803206, 4.285485468091731)


# evidence of power

In [25]:
a1,a2 = np.sqrt(1.09-1), 0.00
num_params= 9
num_sims = 100

def gen_data2(nobs=1000, a1=np.sqrt(1.09-1), a2=0.00 , num_params=19):
    x = np.random.normal(scale=1., size=(nobs,1+num_params))
    e = np.random.normal(loc=0.0, scale=1.0, size=nobs)
    y = 1 + a1*x[:,0] + a2/np.sqrt(num_params)*x[:,1:num_params].sum(axis=1) + e
    return y,x,nobs

In [26]:
a1,a2 = np.sqrt(1.09-1), 0.00
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data2(nobs=250, a1=a1, a2=a2, num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.75 & 0.37 & 0.39 & 0.37 & 0.45   \\
Model 1 & 0.25 & 0.63 & 0.61 & 0.63 & 0.55   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.75, 0.25, 0.  ]), array([0.37, 0.63, 0.  ]), array([0.39, 0.61, 0.  ]), array([0.37, 0.63, 0.  ]), array([0.45, 0.55, 0.  ]), 7.486322443396506, 4.740290387951998, 5.284054315589632)


In [27]:
a1,a2 = np.sqrt(1.09**.5-1), 0.00
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data2(nobs=500, a1=a1, a2=a2, num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.85 & 0.40 & 0.41 & 0.41 & 0.46   \\
Model 1 & 0.15 & 0.60 & 0.59 & 0.59 & 0.54   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.85, 0.15, 0.  ]), array([0.4, 0.6, 0. ]), array([0.41, 0.59, 0.  ]), array([0.41, 0.59, 0.  ]), array([0.46, 0.54, 0.  ]), 7.531409702612514, 4.754170647565862, 5.359266201953576)


In [28]:
a1,a2 = 0.00,np.sqrt(1.09-1)
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data2(nobs=250, a1=a1, a2=a2, num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.17 & 0.52 & 0.55 & 0.50 & 0.64   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.83 & 0.48 & 0.45 & 0.50 & 0.36   \\
\hline
\end{tabular}
(array([0.17, 0.  , 0.83]), array([0.52, 0.  , 0.48]), array([0.55, 0.  , 0.45]), array([0.5, 0. , 0.5]), array([0.64, 0.  , 0.36]), -13.533109143077308, 4.59562633408981, 5.157916972517196)


In [29]:
a1,a2 =  0.00,np.sqrt(1.09**.5-1)
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data2(nobs=500, a1=a1, a2=a2, num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.13 & 0.54 & 0.53 & 0.54 & 0.61   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.87 & 0.46 & 0.47 & 0.46 & 0.39   \\
\hline
\end{tabular}
(array([0.13, 0.  , 0.87]), array([0.54, 0.  , 0.46]), array([0.53, 0.  , 0.47]), array([0.54, 0.  , 0.46]), array([0.61, 0.  , 0.39]), -12.995258121314219, 4.410768245641795, 5.076459605093277)
