In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from statsmodels.base.model import GenericLikelihoodModel
import scipy.stats as stats
import sys

sys.path.append("../")
import vuong_tests3

In [2]:
class OLS_loglike(GenericLikelihoodModel):
    
    def __init__(self, *args,ols=False, **kwargs):
        super(OLS_loglike,self).__init__(*args,**kwargs)
        self.ols = ols

    def loglikeobs(self, params):
        y = self.endog
        x = self.exog
        mu_y = np.matmul(x,params)  
        resid = y - mu_y
        sigma = np.sqrt(np.sum(resid**2)/resid.shape[0])
        pr_y = stats.norm.logpdf( resid, loc=0,scale=sigma )
        return pr_y


def setup_shi(yn,xn,return_model=False,num_params=4):
    x1n,x2n = xn[:,0],xn[:,1:num_params]
    
    # model 1 grad, etc.
    model1 = sm.OLS(yn,sm.add_constant(x1n))
    model1_fit = model1.fit(disp=False)
    params1 = (model1_fit.params)
    
    model1_deriv = OLS_loglike(yn,sm.add_constant(x1n))
    ll1 = model1_deriv.loglikeobs(model1_fit.params)
    grad1 =  model1_deriv.score_obs(model1_fit.params)    
    hess1 = model1_deriv.hessian(model1_fit.params)
    
    #model 2 grad, etc.
    model2 = sm.OLS(yn,sm.add_constant(x2n))
    model2_fit = model2.fit(disp=False)
    params2 = (model2_fit.params)
    
    model2_deriv = OLS_loglike(yn,sm.add_constant(x2n))
    ll2 = model2_deriv.loglikeobs(model2_fit.params)
    grad2 =  model2_deriv.score_obs(model2_fit.params)    
    hess2 = model2_deriv.hessian(model2_fit.params)
    
    if return_model:
        return ll1,grad1,hess1,params1,model1,ll2,grad2,hess2,params2,model2
    return ll1,grad1,hess1,params1,ll2,grad2,hess2,params2

def gen_data(nobs=1000, a=0.25, num_params=4):
    x = np.random.normal(scale=1., size=(nobs,1+num_params))
    e = np.random.normal(loc=0.0, scale=1.0, size=nobs)
    y = 1 + a*x[:,0] + a/np.sqrt(num_params)*x[:,1:num_params].sum(axis=1) + e
    return y,x,nobs

yn,xn,nobs = gen_data()
ll1,grad1,hess1,params1,ll2,grad2,hess2,params2 = setup_shi(yn,xn,return_model=False,num_params=15)

# a  = .25, k= 4, something is not right...

In [3]:
a = 0.25
num_params=4
num_sims = 100

In [4]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, a=a,  num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.98 & 0.97 & 0.97 & 0.96 & 0.99   \\
Model 1 & 0.02 & 0.03 & 0.03 & 0.04 & 0.01   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.98, 0.02, 0.  ]), array([0.97, 0.03, 0.  ]), array([0.97, 0.03, 0.  ]), array([0.96, 0.04, 0.  ]), array([0.99, 0.01, 0.  ]), 1.1673677864480618, 4.642409507809863, 5.191941856955204)


In [5]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, a=a,  num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.89 & 0.89 & 0.89 & 0.87 & 0.90   \\
Model 1 & 0.10 & 0.10 & 0.10 & 0.12 & 0.10   \\
Model 2 & 0.01 & 0.01 & 0.01 & 0.01 & 0.00   \\
\hline
\end{tabular}
(array([0.89, 0.1 , 0.01]), array([0.89, 0.1 , 0.01]), array([0.89, 0.1 , 0.01]), array([0.87, 0.12, 0.01]), array([0.9, 0.1, 0. ]), 3.642376426853186, 8.463667694313706, 7.323749770681335)


# a  = .25, k= 9

In [6]:
a = 0.25
num_params=9
num_sims = 100

In [7]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, a=a,  num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.96 & 0.96 & 0.97 & 0.95 & 0.97   \\
Model 1 & 0.01 & 0.03 & 0.03 & 0.03 & 0.03   \\
Model 2 & 0.03 & 0.01 & 0.00 & 0.02 & 0.00   \\
\hline
\end{tabular}
(array([0.96, 0.01, 0.03]), array([0.96, 0.03, 0.01]), array([0.97, 0.03, 0.  ]), array([0.95, 0.03, 0.02]), array([0.97, 0.03, 0.  ]), -2.578657016902284, 5.125844644903456, 5.754587225946249)


In [8]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, a=a,  num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.92 & 0.93 & 0.96 & 0.95 & 0.98   \\
Model 1 & 0.01 & 0.03 & 0.02 & 0.02 & 0.01   \\
Model 2 & 0.07 & 0.04 & 0.02 & 0.03 & 0.01   \\
\hline
\end{tabular}
(array([0.92, 0.01, 0.07]), array([0.93, 0.03, 0.04]), array([0.96, 0.02, 0.02]), array([0.95, 0.02, 0.03]), array([0.98, 0.01, 0.01]), -2.2032761180447666, 7.8088490241344495, 7.6798122991891455)


# a  = 0, k= 9

In [9]:
a = 0.00 
num_params=9
num_sims = 100

In [10]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, a=a,  num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.92 & 0.98 & 0.97 & 0.97 & 0.99   \\
Model 1 & 0.00 & 0.02 & 0.03 & 0.03 & 0.01   \\
Model 2 & 0.08 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.92, 0.  , 0.08]), array([0.98, 0.02, 0.  ]), array([0.97, 0.03, 0.  ]), array([0.97, 0.03, 0.  ]), array([0.99, 0.01, 0.  ]), -3.6931913809464754, 2.196646186731224, 2.9134683729275856)


In [11]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, a=a,  num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.97 & 1.00 & 1.00 & 0.99 & 1.00   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.01 & 0.00   \\
Model 2 & 0.03 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.97, 0.  , 0.03]), array([1., 0., 0.]), array([1., 0., 0.]), array([0.99, 0.01, 0.  ]), array([1., 0., 0.]), -3.62396910892792, 2.0272880382140688, 2.9911218935668256)


# a  = .25

In [12]:
a = 0.25
num_params=19
num_sims = 100

In [13]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, a=a,  num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.82 & 0.94 & 0.98 & 0.96 & 0.98   \\
Model 1 & 0.00 & 0.04 & 0.02 & 0.03 & 0.02   \\
Model 2 & 0.18 & 0.02 & 0.00 & 0.01 & 0.00   \\
\hline
\end{tabular}
(array([0.82, 0.  , 0.18]), array([0.94, 0.04, 0.02]), array([0.98, 0.02, 0.  ]), array([0.96, 0.03, 0.01]), array([0.98, 0.02, 0.  ]), -7.442112830180388, 6.2709625722133, 6.690048436287557)


In [14]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, a=a,  num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.92 & 0.98 & 0.99 & 0.99 & 1.00   \\
Model 1 & 0.00 & 0.02 & 0.01 & 0.01 & 0.00   \\
Model 2 & 0.08 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.92, 0.  , 0.08]), array([0.98, 0.02, 0.  ]), array([0.99, 0.01, 0.  ]), array([0.99, 0.01, 0.  ]), array([1., 0., 0.]), -7.070221986638262, 6.4560446645287906, 8.357427916396352)


In [15]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=1000, a=a,  num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.93 & 0.96 & 0.96 & 0.95 & 0.96   \\
Model 1 & 0.00 & 0.04 & 0.04 & 0.05 & 0.04   \\
Model 2 & 0.07 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.93, 0.  , 0.07]), array([0.96, 0.04, 0.  ]), array([0.96, 0.04, 0.  ]), array([0.95, 0.05, 0.  ]), array([0.96, 0.04, 0.  ]), -5.520680432468506, 10.600920462661747, 11.30021043041742)


# a = 0

In [16]:
a = 0.0
num_params=19
num_sims = 100

In [17]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=250, a=a,  num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.43 & 0.99 & 1.00 & 1.00 & 1.00   \\
Model 1 & 0.00 & 0.01 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.57 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.43, 0.  , 0.57]), array([0.99, 0.01, 0.  ]), array([1., 0., 0.]), array([1., 0., 0.]), array([1., 0., 0.]), -8.735169902808126, 3.145127379560734, 4.276995578831395)


In [18]:
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data(nobs=500, a=a,  num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.48 & 0.99 & 0.99 & 0.98 & 0.99   \\
Model 1 & 0.00 & 0.01 & 0.01 & 0.02 & 0.01   \\
Model 2 & 0.52 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.48, 0.  , 0.52]), array([0.99, 0.01, 0.  ]), array([0.99, 0.01, 0.  ]), array([0.98, 0.02, 0.  ]), array([0.99, 0.01, 0.  ]), -8.958073921108598, 3.460337750922793, 4.315854145117985)


# evidence of power

In [19]:
a1,a2 = np.sqrt(1.09-1), 0.00
num_params= 9
num_sims = 100

def gen_data2(nobs=1000, a1=np.sqrt(1.09-1), a2=0.00 , num_params=19):
    x = np.random.normal(scale=1., size=(nobs,1+num_params))
    e = np.random.normal(loc=0.0, scale=1.0, size=nobs)
    y = 1 + a1*x[:,0] + a2/np.sqrt(num_params)*x[:,1:num_params].sum(axis=1) + e
    return y,x,nobs

In [20]:
a1,a2 = np.sqrt(1.09-1), 0.00
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data2(nobs=250, a1=a1, a2=a2, num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.79 & 0.48 & 0.47 & 0.48 & 0.54   \\
Model 1 & 0.21 & 0.52 & 0.53 & 0.52 & 0.46   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.79, 0.21, 0.  ]), array([0.48, 0.52, 0.  ]), array([0.47, 0.53, 0.  ]), array([0.48, 0.52, 0.  ]), array([0.54, 0.46, 0.  ]), 6.670266026830381, 4.452001406383617, 5.10792318263656)


In [21]:
a1,a2 = np.sqrt(1.09**.5-1), 0.00
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data2(nobs=500, a1=a1, a2=a2, num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.84 & 0.49 & 0.51 & 0.47 & 0.57   \\
Model 1 & 0.16 & 0.51 & 0.49 & 0.53 & 0.43   \\
Model 2 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.84, 0.16, 0.  ]), array([0.49, 0.51, 0.  ]), array([0.51, 0.49, 0.  ]), array([0.47, 0.53, 0.  ]), array([0.57, 0.43, 0.  ]), 7.113031428004619, 4.683785079681917, 5.513668864442714)


In [22]:
a1,a2 = 0.00,np.sqrt(1.09-1)
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data2(nobs=250, a1=a1, a2=a2, num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.17 & 0.58 & 0.59 & 0.57 & 0.68   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.83 & 0.42 & 0.41 & 0.43 & 0.32   \\
\hline
\end{tabular}
(array([0.17, 0.  , 0.83]), array([0.58, 0.  , 0.42]), array([0.59, 0.  , 0.41]), array([0.57, 0.  , 0.43]), array([0.68, 0.  , 0.32]), -12.956358730104933, 4.328524151558365, 5.06685581257543)


In [23]:
a1,a2 =  0.00,np.sqrt(1.09**.5-1)
setup_shi_ex  = lambda yn,xn: setup_shi(yn,xn,num_params=num_params)
gen_data_ex = lambda : gen_data2(nobs=500, a1=a1, a2=a2, num_params=num_params)
mc_out = vuong_tests3.monte_carlo(num_sims,gen_data_ex,setup_shi_ex)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-pt & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.16 & 0.53 & 0.52 & 0.52 & 0.58   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.84 & 0.47 & 0.48 & 0.48 & 0.42   \\
\hline
\end{tabular}
(array([0.16, 0.  , 0.84]), array([0.53, 0.  , 0.47]), array([0.52, 0.  , 0.48]), array([0.52, 0.  , 0.48]), array([0.58, 0.  , 0.42]), -13.689689339666835, 5.046445197555612, 5.167552660041278)
