In [4]:
%load_ext autoreload
%autoreload 2

import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import scipy.stats as stats
import sys

sys.path.append("../")
import vuong_tests3

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [5]:
def compute_loglike(resid):
    sigma = np.sqrt(np.sum(resid**2)/resid.shape[0])
    ll = np.log(stats.norm.pdf(resid,loc=0,scale=sigma))
    return ll

def compute_score(yn,xn,params):
    
    xn = sm.add_constant(xn)
    resid = yn - np.matmul(xn,params)
    
    k = len(params)
    scale = (resid**2).mean()
    
    tile_resid = np.tile( resid, k)
    tile_resid = np.reshape(tile_resid, (k,xn.shape[0]) ).transpose()
    grad = tile_resid*xn/scale     
    return grad
    
def compute_hess(yn,xn,params):
    pass


def setup_shi(yn,xn,return_model=False,num_params=15):
    x1n,x2n = xn[:,0],xn[:,1:num_params]
    
    # model 1 grad, etc.
    model1 = sm.OLS(yn,sm.add_constant(x1n))
    model1_fit = model1.fit(disp=False)
    params1 = (model1_fit.params)
    
    ll1 = compute_loglike(model1_fit.resid)
    grad1 =  compute_score(yn,x1n,model1_fit.params)
    hess1 = model1.hessian(model1_fit.params)
    
    #model 2 grad, etc.
    model2 = sm.OLS(yn,sm.add_constant(x2n))
    model2_fit = model2.fit(disp=False)
    params2 = (model2_fit.params)
    
    ll2 = compute_loglike(model2_fit.resid)
    grad2 =  compute_score(yn,x2n,model2_fit.params)
    hess2 = model2.hessian(model2_fit.params)
    
    if return_model:
        return ll1,grad1,hess1,params1,model1,ll2,grad2,hess2,params2,model2
    return ll1,grad1,hess1,params1,ll2,grad2,hess2,params2


# a  = .25

In [6]:
def gen_data(nobs=1000, a=0.25, num_params=15):
    x = np.random.normal(scale=3., size=(nobs,1+num_params))
    e = np.random.normal(loc=0.0, scale=1.0, size=nobs)
    y = 1 + a*x[:,0] + a/np.sqrt(num_params)*x[:,1:num_params+1].sum(axis=1) + e
    return y,x,nobs

gen_data_ex = lambda : gen_data(nobs=1000, a=0.25, num_params=15)
mc_out = vuong_tests3.monte_carlo(1000,gen_data_ex,setup_shi)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-bc & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.93 & 0.94 & 0.94 & 0.94 & 0.94   \\
Model 1 & 0.06 & 0.06 & 0.06 & 0.06 & 0.06   \\
Model 2 & 0.01 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.928, 0.059, 0.013]), array([0.938, 0.059, 0.003]), array([0.939, 0.059, 0.002]), array([0.938, 0.059, 0.003]), array([0.939, 0.059, 0.002]), 7.00464336115551, 24.465497461589536, 24.172227129017035)


In [7]:
gen_data_ex = lambda : gen_data(nobs=500, a=0.25, num_params=15)
mc_out = vuong_tests3.monte_carlo(1000,gen_data_ex,setup_shi)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-bc & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.95 & 0.97 & 0.97 & 0.97 & 0.97   \\
Model 1 & 0.03 & 0.03 & 0.03 & 0.03 & 0.03   \\
Model 2 & 0.02 & 0.00 & 0.00 & 0.01 & 0.00   \\
\hline
\end{tabular}
(array([0.95 , 0.027, 0.023]), array([0.97 , 0.027, 0.003]), array([0.969, 0.027, 0.004]), array([0.968, 0.027, 0.005]), array([0.97 , 0.027, 0.003]), -0.1027299514889731, 16.890402511514225, 17.155496315549406)


In [8]:
gen_data_ex = lambda : gen_data(nobs=250, a=0.25, num_params=15)
mc_out = vuong_tests3.monte_carlo(1000,gen_data_ex,setup_shi)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-bc & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.93 & 0.98 & 0.98 & 0.98 & 0.99   \\
Model 1 & 0.01 & 0.01 & 0.01 & 0.01 & 0.01   \\
Model 2 & 0.06 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.925, 0.014, 0.061]), array([0.984, 0.014, 0.002]), array([0.983, 0.014, 0.003]), array([0.984, 0.014, 0.002]), array([0.986, 0.014, 0.   ]), -4.2112830467208, 12.46606814117043, 12.136453886165292)


# a  = .125

In [9]:
gen_data_ex = lambda : gen_data(nobs=1000, a=0.125, num_params=15)
mc_out = vuong_tests3.monte_carlo(1000,gen_data_ex,setup_shi)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-bc & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.95 & 0.98 & 0.98 & 0.98 & 0.98   \\
Model 1 & 0.01 & 0.01 & 0.01 & 0.01 & 0.01   \\
Model 2 & 0.04 & 0.01 & 0.01 & 0.01 & 0.01   \\
\hline
\end{tabular}
(array([0.948, 0.013, 0.039]), array([0.978, 0.013, 0.009]), array([0.979, 0.013, 0.008]), array([0.978, 0.013, 0.009]), array([0.981, 0.013, 0.006]), -3.126398788717006, 15.273729166214324, 15.308045039558609)


In [10]:
gen_data_ex = lambda : gen_data(nobs=500, a=0.125, num_params=15)
mc_out = vuong_tests3.monte_carlo(1000,gen_data_ex,setup_shi)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-bc & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.94 & 0.99 & 0.99 & 0.99 & 0.99   \\
Model 1 & 0.01 & 0.01 & 0.01 & 0.01 & 0.01   \\
Model 2 & 0.05 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.944, 0.007, 0.049]), array([0.992, 0.007, 0.001]), array([0.992, 0.007, 0.001]), array([0.992, 0.007, 0.001]), array([0.992, 0.007, 0.001]), -4.1468054634982146, 10.889293741453333, 11.040234272145536)


In [11]:
gen_data_ex = lambda : gen_data(nobs=250, a=0.125, num_params=15)
mc_out = vuong_tests3.monte_carlo(1000,gen_data_ex,setup_shi)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-bc & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.91 & 0.99 & 0.99 & 0.99 & 0.99   \\
Model 1 & 0.01 & 0.01 & 0.01 & 0.01 & 0.01   \\
Model 2 & 0.09 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.91 , 0.005, 0.085]), array([0.994, 0.005, 0.001]), array([0.993, 0.005, 0.002]), array([0.994, 0.005, 0.001]), array([0.994, 0.005, 0.001]), -5.519932940631679, 7.880307229519544, 8.122512662850248)


# a = 0

In [12]:
gen_data_ex = lambda : gen_data(nobs=1000, a=0.0, num_params=15)
mc_out = vuong_tests3.monte_carlo(1000,gen_data_ex,setup_shi)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-bc & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.72 & 1.00 & 1.00 & 1.00 & 1.00   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.28 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.721, 0.   , 0.279]), array([1., 0., 0.]), array([1., 0., 0.]), array([1., 0., 0.]), array([1., 0., 0.]), -6.627882929155079, 2.835444238319601, 3.804666555189614)


In [13]:
gen_data_ex = lambda : gen_data(nobs=500, a=0.0, num_params=15)
mc_out = vuong_tests3.monte_carlo(1000,gen_data_ex,setup_shi)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-bc & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.73 & 1.00 & 1.00 & 1.00 & 1.00   \\
Model 1 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00   \\
Model 2 & 0.27 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.732, 0.   , 0.268]), array([0.998, 0.002, 0.   ]), array([0.998, 0.002, 0.   ]), array([0.998, 0.002, 0.   ]), array([0.999, 0.001, 0.   ]), -6.583812776023755, 2.7504561840508877, 3.795966688576055)


In [14]:
gen_data_ex = lambda : gen_data(nobs=250, a=0.0, num_params=15)
mc_out = vuong_tests3.monte_carlo(1000,gen_data_ex,setup_shi)
vuong_tests3.print_mc(mc_out)
print(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-bc & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.69 & 0.99 & 0.99 & 0.99 & 1.00   \\
Model 1 & 0.00 & 0.01 & 0.01 & 0.01 & 0.00   \\
Model 2 & 0.31 & 0.00 & 0.00 & 0.00 & 0.00   \\
\hline
\end{tabular}
(array([0.688, 0.   , 0.312]), array([0.995, 0.005, 0.   ]), array([0.994, 0.006, 0.   ]), array([0.994, 0.006, 0.   ]), array([0.997, 0.003, 0.   ]), -6.776967658143603, 2.8135620847609655, 3.784296133594625)


# other weird DGPs

In [20]:
def gen_data(beta=0):
    nobs = 250
    #x = np.random.normal(low=-3., high=3., size=(nobs,3))
    x = np.random.normal(scale=3., size=(nobs,4))
    e = np.random.normal(loc=0.0, scale=1.0, size=nobs)
    y = 1 + 1/np.sqrt(2)*x[:,3] + 1/np.sqrt(2)*x[:,2] + 1*x[:,0] + beta * x[:,1] + e
    return y,x,nobs

yn,xn,nobs = gen_data()
ll1,grad1,hess1,ll2,k1, grad2,hess2,k2 = setup_shi(yn,xn)


mc_out = vuong_tests3.monte_carlo(100,gen_data,setup_shi)
vuong_tests3.print_mc(mc_out)

\begin{tabular}{|c|c|c|c|c|c|}
\hline
Model &  Normal & Bootstrap & Bootstrap-bc & Bootstrap-bc & Shi (2015) \\ \hline \hline
No selection & 0.95 & 0.94 & 0.94 & 0.97 & 0.98   \\
Model 1 & 0.01 & 0.03 & 0.02 & 0.01 & 0.01   \\
Model 2 & 0.04 & 0.03 & 0.04 & 0.02 & 0.01   \\
\hline
\end{tabular}
